// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'config.dart';

// **************************************************************************
// SwiftGenerator
// **************************************************************************

// **************************************************************************
// generated by swift_composer at 2022-09-04 12:20:41.206974
// **************************************************************************
// CONFIG
// no config file for root: /home/fsw/workspace/swift_shop/packages/swift_composer/.dart_tool/..//lib/swift_composer.di.yaml
// config file for m1: /home/fsw/workspace/swift_shop/packages/swift_composer/test/config/../lib/foo.di.yaml
// config file for m2: /home/fsw/workspace/swift_shop/packages/swift_composer/test/config/../lib/foo2.di.yaml
// no config file for generics: /home/fsw/workspace/swift_shop/packages/swift_composer/test/config/../lib/generics.di.yaml
// config file for root: /home/fsw/workspace/swift_shop/packages/swift_composer/test/config/config.di.yaml
// **************************************************************************
// MERGED CONFIG
// m1.Foo: {stringField: FooField, integerField: 124}
// m1.FooChild: {stringField: FooChildField, doubleField: 0.55, booleanField: true}
// m1.FooChild2: {stringField: FooChild2Field, doubleField: 0.55, booleanField: true}
// m2.Foo: {stringField2: Foo2Field}
// VirtualTypeX: {extends: m1.SimpleGeneric<m1.Foo>, stringField: FooStringField2}
// **************************************************************************
// ALL TYPES INFO
// **************************************************************************
// SubtypesOf => SubtypesOf  GENERIC [T = T   473656069 = 473656069   473656069 = TypeParameterTypeImpl]
// AnnotatedWith => AnnotatedWith   [      ]
// Pluggable => Pluggable   [      ]
// TypePlugin => TypePlugin  GENERIC [T = T   380287154 = 380287154   380287154 = TypeParameterTypeImpl]
// m1.Foo => m1.Foo INTERCEPTED  [      ]
// m1.FooChild => m1.FooChild INTERCEPTED  [      ]
// m1.FooChild2 => m1.FooChild2 INTERCEPTED  [      ]
// m2.Foo => m2.Foo INTERCEPTED  [      ]
// generics.SimpleGeneric => generics.SimpleGeneric  GENERIC [T = T   516375725 = 516375725   516375725 = TypeParameterTypeImpl]
// generics.Param => generics.Param INTERCEPTED  [      ]
// generics.SimpleSpecific => generics.SimpleSpecific INTERCEPTED  [T = Param   516375725 = 356184557   516375725 = InterfaceTypeImpl]
// generics.ComplexGeneric => generics.ComplexGeneric  GENERIC [A = A,B = B   99844900 = 99844900,364591990 = 364591990   99844900 = TypeParameterTypeImpl,364591990 = TypeParameterTypeImpl]
// generics.SuperComplexGeneric => generics.SuperComplexGeneric  GENERIC [A = A,B = B   517102781 = 517102781,258296657 = 258296657   517102781 = TypeParameterTypeImpl,258296657 = TypeParameterTypeImpl]
// Container => Container INTERCEPTED  [      ]
// Object => Object   [      ]
// String => String   [T = String   99862877 = 55285317   99862877 = InterfaceTypeImpl]
// List<String> => List<String>   [T = E,E = String   265238202 = 263610483,263610483 = 55285317   265238202 = TypeParameterTypeImpl,263610483 = InterfaceTypeImpl]
// T => T   [      ]
// List<T> => List<T>   [T = E,E = T   265238202 = 263610483,263610483 = 473656069   265238202 = TypeParameterTypeImpl,263610483 = TypeParameterTypeImpl]
// dynamic => dynamic   [      ]
// ST => ST   [      ]
// int => int   [T = num   99862877 = 235444537   99862877 = InterfaceTypeImpl]
// double => double   [T = num   99862877 = 235444537   99862877 = InterfaceTypeImpl]
// bool => bool   [      ]
// String? => String?   [T = String   99862877 = 55285317   99862877 = InterfaceTypeImpl]
// void => void   [      ]
// generics.SimpleGeneric<generics.Param> => generics.SimpleGeneric<generics.Param> INTERCEPTED  [T = Param   516375725 = 356184557   516375725 = InterfaceTypeImpl]
// A => A   [      ]
// B => B   [      ]
// generics.ComplexGeneric<generics.Param,A> => generics.ComplexGeneric<generics.Param,A>   [A = Param,B = A   99844900 = 356184557,364591990 = 517102781   99844900 = InterfaceTypeImpl,364591990 = TypeParameterTypeImpl]
// generics.SimpleGeneric<m1.Foo> => generics.SimpleGeneric<m1.Foo> INTERCEPTED  [T = Foo   516375725 = 4632883   516375725 = InterfaceTypeImpl]
// generics.SimpleGeneric<m2.Foo> => generics.SimpleGeneric<m2.Foo> INTERCEPTED  [T = Foo   516375725 = 170770176   516375725 = InterfaceTypeImpl]
// **************************************************************************
// no interceptor for [SubtypesOf]
// type arguments[1]:
// T[473656069] => T[473656069]
// type arguments[2]:
// can be singleton: FALSE
// parameter: T 473656069
// argument: T 473656069
// parent: Object [@pragma pragma(String name, [Object? options])]
// CONFIG
// config: SubtypesOf 1
// TYPE PATH:
//  SubtypesOf
// **************************************************************************
// no interceptor for [AnnotatedWith]
// type arguments[1]:
// type arguments[2]:
// can be singleton: FALSE
// parent: Object [@pragma pragma(String name, [Object? options])]
// CONFIG
// config: AnnotatedWith 1
// TYPE PATH:
//  AnnotatedWith
// **************************************************************************
// no interceptor for [Pluggable]
// type arguments[1]:
// type arguments[2]:
// can be singleton: FALSE
// parent: Object [@pragma pragma(String name, [Object? options])]
// CONFIG
// config: Pluggable 1
// TYPE PATH:
//  Pluggable
// **************************************************************************
// no interceptor for [TypePlugin]
// type arguments[1]:
// T[380287154] => T[380287154]
// type arguments[2]:
// can be singleton: FALSE
// parameter: T 380287154
// argument: T 380287154
// parent: Object [@pragma pragma(String name, [Object? options])]
// CONFIG
// config: TypePlugin 1
// TYPE PATH:
//  TypePlugin
// **************************************************************************
// interceptor for [m1.Foo]
// type arguments[1]:
// type arguments[2]:
// can be singleton: TRUE
// parent: Object [@pragma pragma(String name, [Object? options])]
// parent: Pluggable []
// CONFIG
// config: m1.Foo 1
// config: stringField FooField
// config: integerField 124
// TYPE PATH:
//  m1.Foo
class $m1_Foo extends m1.Foo implements Pluggable {
  $m1_Foo() {}
  T plugin<T>() {
    throw new Exception('no plugin for this type');
  }

// String className
// c: String
  String get className => "m1.Foo";
// String stringField
// c: String
  String get stringField => "FooField";
// int integerField
// c: int
  int get integerField => 124;
}

// **************************************************************************
// interceptor for [m1.FooChild]
// type arguments[1]:
// type arguments[2]:
// can be singleton: TRUE
// parent: Foo [@bool get Compose]
// parent: Object [@pragma pragma(String name, [Object? options])]
// parent: Pluggable []
// CONFIG
// config: m1.FooChild 1
// config: stringField FooChildField
// config: doubleField 0.55
// config: booleanField true
// config: m1.Foo 2
// config: integerField 124
// TYPE PATH:
//  m1.FooChild
//  m1.Foo
class $m1_FooChild extends m1.FooChild implements Pluggable {
  $m1_FooChild() {}
  T plugin<T>() {
    throw new Exception('no plugin for this type');
  }

// double doubleField
// c: double
  double get doubleField => 0.55;
// bool booleanField
// c: bool
  bool get booleanField => true;
// String className
// c: String
  String get className => "m1.FooChild";
// String stringField
// c: String
  String get stringField => "FooChildField";
// int integerField
// c: int
  int get integerField => 124;
}

// **************************************************************************
// interceptor for [m1.FooChild2]
// type arguments[1]:
// type arguments[2]:
// can be singleton: FALSE
// parent: Foo [@bool get Compose]
// parent: Object [@pragma pragma(String name, [Object? options])]
// parent: Pluggable []
// CONFIG
// config: m1.FooChild2 1
// config: stringField FooChild2Field
// config: doubleField 0.55
// config: booleanField true
// config: m1.Foo 2
// config: integerField 124
// TYPE PATH:
//  m1.FooChild2
//  m1.Foo
class $m1_FooChild2 extends m1.FooChild2 implements Pluggable {
  $m1_FooChild2(requiredString) {
//String
    this.requiredString = requiredString;
  }
  T plugin<T>() {
    throw new Exception('no plugin for this type');
  }

// String requiredString
// c: String
// String className
// c: String
  String get className => "m1.FooChild2";
// String stringField
// c: String
  String get stringField => "FooChild2Field";
// int integerField
// c: int
  int get integerField => 124;
}

// **************************************************************************
// interceptor for [m2.Foo]
// type arguments[1]:
// type arguments[2]:
// can be singleton: TRUE
// parent: Object [@pragma pragma(String name, [Object? options])]
// CONFIG
// config: m2.Foo 1
// config: stringField2 Foo2Field
// TYPE PATH:
//  m2.Foo
class $m2_Foo extends m2.Foo implements Pluggable {
  $m2_Foo() {}
  T plugin<T>() {
    throw new Exception('no plugin for this type');
  }

// String className
// c: String
  String get className => "m2.Foo";
// String? stringField2
// c: String?
  String? get stringField2 => "Foo2Field";
}

// **************************************************************************
// no interceptor for [generics.SimpleGeneric]
// type arguments[1]:
// T[516375725] => T[516375725]
// type arguments[2]:
// can be singleton: FALSE
// parameter: T 516375725
// argument: T 516375725
// parent: Object [@pragma pragma(String name, [Object? options])]
// parent: Pluggable []
// CONFIG
// config: generics.SimpleGeneric 1
// TYPE PATH:
//  generics.SimpleGeneric
// **************************************************************************
// interceptor for [generics.Param]
// type arguments[1]:
// type arguments[2]:
// can be singleton: TRUE
// parent: Object [@pragma pragma(String name, [Object? options])]
// CONFIG
// config: generics.Param 1
// TYPE PATH:
//  generics.Param
class $generics_Param extends generics.Param implements Pluggable {
  $generics_Param() {}
  T plugin<T>() {
    throw new Exception('no plugin for this type');
  }
}

// **************************************************************************
// interceptor for [generics.SimpleSpecific]
// type arguments[1]:
// T[516375725] => Param[356184557]
// type arguments[2]:
// can be singleton: TRUE
// parent: SimpleGeneric [@bool get Compose]
// parameter: T 516375725
// argument: Param 356184557
// parent: Object [@pragma pragma(String name, [Object? options])]
// parent: Pluggable []
// CONFIG
// config: generics.SimpleSpecific 1
// config: generics.SimpleGeneric 2
// TYPE PATH:
//  generics.SimpleSpecific
//  generics.SimpleGeneric
class $generics_SimpleSpecific extends generics.SimpleSpecific
    implements Pluggable {
  $generics_SimpleSpecific() {}
  T plugin<T>() {
    throw new Exception('no plugin for this type');
  }
}

// **************************************************************************
// no interceptor for [generics.ComplexGeneric]
// type arguments[1]:
// A[99844900] => A[99844900]
// B[364591990] => B[364591990]
// type arguments[2]:
// can be singleton: FALSE
// parameter: A 99844900
// parameter: B 364591990
// argument: A 99844900
// argument: B 364591990
// parent: Object [@pragma pragma(String name, [Object? options])]
// CONFIG
// config: generics.ComplexGeneric 1
// TYPE PATH:
//  generics.ComplexGeneric
// **************************************************************************
// no interceptor for [generics.SuperComplexGeneric]
// type arguments[1]:
// A[99844900] => Param[356184557]
// B[364591990] => A[517102781]
// A[517102781] => A[517102781]
// B[258296657] => B[258296657]
// type arguments[2]:
// can be singleton: FALSE
// parameter: A 517102781
// parameter: B 258296657
// argument: A 517102781
// argument: B 258296657
// parent: ComplexGeneric [@bool get Compose]
// parameter: A 99844900
// parameter: B 364591990
// argument: Param 356184557
// argument: A 517102781
// parent: Object [@pragma pragma(String name, [Object? options])]
// CONFIG
// config: generics.SuperComplexGeneric 1
// config: generics.ComplexGeneric 2
// TYPE PATH:
//  generics.SuperComplexGeneric
//  generics.ComplexGeneric
// **************************************************************************
// interceptor for [Container]
// type arguments[1]:
// type arguments[2]:
// can be singleton: FALSE
// parent: Object [@pragma pragma(String name, [Object? options])]
// CONFIG
// config: Container 1
// TYPE PATH:
//  Container
class $Container extends Container implements Pluggable {
  $Container(fooRequired, genericRequired) {
//Foo
//create
//m1.Foo
// c: m1.Foo
// c: m1.FooChild
// c: m1.FooChild2
    this.fooCreated = new $m1_Foo();
//SimpleGeneric<Foo>
//create
//generics.SimpleGeneric<m1.Foo>
// c: generics.SimpleGeneric<m1.Foo>
    this.genericCreated = new $generics_SimpleGeneric_m1_Foo_();
//Foo
    this.fooRequired = fooRequired;
//SimpleGeneric<Foo>
    this.genericRequired = genericRequired;
  }
  T plugin<T>() {
    throw new Exception('no plugin for this type');
  }

// m1.Foo fooCreated
// c: m1.Foo
// c: m1.FooChild
// c: m1.FooChild2
// generics.SimpleGeneric<m1.Foo> genericCreated
// c: generics.SimpleGeneric<m1.Foo>
// m1.Foo fooRequired
// c: m1.Foo
// c: m1.FooChild
// c: m1.FooChild2
// generics.SimpleGeneric<m2.Foo> genericRequired
// c: generics.SimpleGeneric<m2.Foo>
// m1.Foo fooInjected
// c: m1.Foo
// c: m1.FooChild
// c: m1.FooChild2
  m1.Foo get fooInjected => $om.m1_Foo;
// generics.SimpleGeneric<m1.Foo> genericInjected
// c: generics.SimpleGeneric<m1.Foo>
  generics.SimpleGeneric<m1.Foo> get genericInjected =>
      $om.generics_SimpleGeneric_m1_Foo_;
}

// **************************************************************************
// no interceptor for [Object]
// type arguments[1]:
// type arguments[2]:
// can be singleton: FALSE
// CONFIG
// config: Object 1
// TYPE PATH:
//  Object
// **************************************************************************
// no interceptor for [String]
// type arguments[1]:
// T[99862877] => String[55285317]
// type arguments[2]:
// can be singleton: FALSE
// parent: Object [@pragma pragma(String name, [Object? options])]
// parent: Comparable []
// parameter: T 99862877
// argument: String 55285317
// parent: Pattern []
// CONFIG
// config: String 1
// TYPE PATH:
//  String
// **************************************************************************
// no interceptor for [List<String>]
// type arguments[1]:
// T[265238202] => E[263610483]
// E[268730869] => E[263610483]
// E[263610483] => String[55285317]
// type arguments[2]:
// ENCLOSING: XXX
// String[312483044]
// can be singleton: FALSE
// parameter: E 263610483
// argument: E 263610483
// parent: Object [@pragma pragma(String name, [Object? options])]
// parent: EfficientLengthIterable []
// parameter: T 265238202
// argument: E 263610483
// parent: Iterable []
// parameter: E 268730869
// argument: E 263610483
// CONFIG
// config: List 1
// TYPE PATH:
//  List
// **************************************************************************
// no interceptor for [T]
// type arguments[1]:
// type arguments[2]:
// **************************************************************************
// no interceptor for [List<T>]
// type arguments[1]:
// T[265238202] => E[263610483]
// E[268730869] => E[263610483]
// E[263610483] => T[473656069]
// type arguments[2]:
// ENCLOSING: NULL
// T[45873792]
// can be singleton: FALSE
// parameter: E 263610483
// argument: E 263610483
// parent: Object [@pragma pragma(String name, [Object? options])]
// parent: EfficientLengthIterable []
// parameter: T 265238202
// argument: E 263610483
// parent: Iterable []
// parameter: E 268730869
// argument: E 263610483
// CONFIG
// config: List 1
// TYPE PATH:
//  List
// **************************************************************************
// no interceptor for [dynamic]
// type arguments[1]:
// type arguments[2]:
// **************************************************************************
// no interceptor for [ST]
// type arguments[1]:
// type arguments[2]:
// **************************************************************************
// no interceptor for [int]
// type arguments[1]:
// T[99862877] => num[235444537]
// type arguments[2]:
// can be singleton: FALSE
// parent: num []
// parent: Object [@pragma pragma(String name, [Object? options])]
// parent: Comparable []
// parameter: T 99862877
// argument: num 235444537
// CONFIG
// config: int 1
// config: num 2
// TYPE PATH:
//  int
//  num
// **************************************************************************
// no interceptor for [double]
// type arguments[1]:
// T[99862877] => num[235444537]
// type arguments[2]:
// can be singleton: FALSE
// parent: num []
// parent: Object [@pragma pragma(String name, [Object? options])]
// parent: Comparable []
// parameter: T 99862877
// argument: num 235444537
// CONFIG
// config: double 1
// config: num 2
// TYPE PATH:
//  double
//  num
// **************************************************************************
// no interceptor for [bool]
// type arguments[1]:
// type arguments[2]:
// can be singleton: FALSE
// parent: Object [@pragma pragma(String name, [Object? options])]
// CONFIG
// config: bool 1
// TYPE PATH:
//  bool
// **************************************************************************
// no interceptor for [String?]
// type arguments[1]:
// T[99862877] => String[55285317]
// type arguments[2]:
// can be singleton: FALSE
// parent: Object [@pragma pragma(String name, [Object? options])]
// parent: Comparable []
// parameter: T 99862877
// argument: String 55285317
// parent: Pattern []
// CONFIG
// config: String 1
// TYPE PATH:
//  String
// **************************************************************************
// no interceptor for [void]
// type arguments[1]:
// type arguments[2]:
// **************************************************************************
// interceptor for [generics.SimpleGeneric<generics.Param>]
// type arguments[1]:
// T[516375725] => Param[356184557]
// type arguments[2]:
// ENCLOSING: XXX
// Param[883615856]
// can be singleton: TRUE
// parameter: T 516375725
// argument: T 516375725
// parent: Object [@pragma pragma(String name, [Object? options])]
// parent: Pluggable []
// CONFIG
// config: generics.SimpleGeneric 1
// TYPE PATH:
//  generics.SimpleGeneric
//parametrized type
class $generics_SimpleGeneric_generics_Param_
    extends generics.SimpleGeneric<generics.Param> implements Pluggable {
  $generics_SimpleGeneric() {}
  T plugin<T>() {
    throw new Exception('no plugin for this type');
  }
}

// **************************************************************************
// no interceptor for [A]
// type arguments[1]:
// type arguments[2]:
// **************************************************************************
// no interceptor for [B]
// type arguments[1]:
// type arguments[2]:
// **************************************************************************
// no interceptor for [generics.ComplexGeneric<generics.Param,A>]
// type arguments[1]:
// A[99844900] => Param[356184557]
// B[364591990] => A[517102781]
// type arguments[2]:
// ENCLOSING: XXX
// Param[883615856]
// ENCLOSING: NULL
// A[419259170]
// can be singleton: FALSE
// parameter: A 99844900
// parameter: B 364591990
// argument: A 99844900
// argument: B 364591990
// parent: Object [@pragma pragma(String name, [Object? options])]
// CONFIG
// config: generics.ComplexGeneric 1
// TYPE PATH:
//  generics.ComplexGeneric
// **************************************************************************
// interceptor for [generics.SimpleGeneric<m1.Foo>]
// type arguments[1]:
// T[516375725] => Foo[4632883]
// type arguments[2]:
// ENCLOSING: XXX
// Foo[267805844]
// can be singleton: TRUE
// parameter: T 516375725
// argument: T 516375725
// parent: Object [@pragma pragma(String name, [Object? options])]
// parent: Pluggable []
// CONFIG
// config: generics.SimpleGeneric 1
// TYPE PATH:
//  generics.SimpleGeneric
//parametrized type
class $generics_SimpleGeneric_m1_Foo_ extends generics.SimpleGeneric<m1.Foo>
    implements Pluggable {
  $generics_SimpleGeneric() {}
  T plugin<T>() {
    throw new Exception('no plugin for this type');
  }
}

// **************************************************************************
// interceptor for [generics.SimpleGeneric<m2.Foo>]
// type arguments[1]:
// T[516375725] => Foo[170770176]
// type arguments[2]:
// ENCLOSING: XXX
// Foo[309028690]
// can be singleton: TRUE
// parameter: T 516375725
// argument: T 516375725
// parent: Object [@pragma pragma(String name, [Object? options])]
// parent: Pluggable []
// CONFIG
// config: generics.SimpleGeneric 1
// TYPE PATH:
//  generics.SimpleGeneric
//parametrized type
class $generics_SimpleGeneric_m2_Foo_ extends generics.SimpleGeneric<m2.Foo>
    implements Pluggable {
  $generics_SimpleGeneric() {}
  T plugin<T>() {
    throw new Exception('no plugin for this type');
  }
}

// **************************************************************************
// no interceptor for [SubtypesOf<T>]
// type arguments[1]:
// T[473656069] => T[473656069]
// type arguments[2]:
// ENCLOSING: NULL
// T[45873792]
// can be singleton: FALSE
// parameter: T 473656069
// argument: T 473656069
// parent: Object [@pragma pragma(String name, [Object? options])]
// CONFIG
// config: SubtypesOf 1
// TYPE PATH:
//  SubtypesOf
// **************************************************************************
// no interceptor for [TypePlugin<T>]
// type arguments[1]:
// T[380287154] => T[380287154]
// type arguments[2]:
// ENCLOSING: NULL
// T[45873792]
// can be singleton: FALSE
// parameter: T 380287154
// argument: T 380287154
// parent: Object [@pragma pragma(String name, [Object? options])]
// CONFIG
// config: TypePlugin 1
// TYPE PATH:
//  TypePlugin
// **************************************************************************
// no interceptor for [generics.SimpleGeneric<T>]
// type arguments[1]:
// T[516375725] => T[516375725]
// type arguments[2]:
// ENCLOSING: NULL
// T[45873792]
// can be singleton: FALSE
// parameter: T 516375725
// argument: T 516375725
// parent: Object [@pragma pragma(String name, [Object? options])]
// parent: Pluggable []
// CONFIG
// config: generics.SimpleGeneric 1
// TYPE PATH:
//  generics.SimpleGeneric
// **************************************************************************
// no interceptor for [generics.ComplexGeneric<A,B>]
// type arguments[1]:
// A[99844900] => A[99844900]
// B[364591990] => B[364591990]
// type arguments[2]:
// ENCLOSING: NULL
// A[419259170]
// ENCLOSING: NULL
// B[424820759]
// can be singleton: FALSE
// parameter: A 99844900
// parameter: B 364591990
// argument: A 99844900
// argument: B 364591990
// parent: Object [@pragma pragma(String name, [Object? options])]
// CONFIG
// config: generics.ComplexGeneric 1
// TYPE PATH:
//  generics.ComplexGeneric
// **************************************************************************
// no interceptor for [generics.SuperComplexGeneric<A,B>]
// type arguments[1]:
// A[99844900] => Param[356184557]
// B[364591990] => A[517102781]
// A[517102781] => A[517102781]
// B[258296657] => B[258296657]
// type arguments[2]:
// ENCLOSING: NULL
// A[419259170]
// ENCLOSING: NULL
// B[424820759]
// can be singleton: FALSE
// parameter: A 517102781
// parameter: B 258296657
// argument: A 517102781
// argument: B 258296657
// parent: ComplexGeneric [@bool get Compose]
// parameter: A 99844900
// parameter: B 364591990
// argument: Param 356184557
// argument: A 517102781
// parent: Object [@pragma pragma(String name, [Object? options])]
// CONFIG
// config: generics.SuperComplexGeneric 1
// config: generics.ComplexGeneric 2
// TYPE PATH:
//  generics.SuperComplexGeneric
//  generics.ComplexGeneric
// **************************************************************************
// no interceptor for [num]
// type arguments[1]:
// T[99862877] => num[235444537]
// type arguments[2]:
// can be singleton: FALSE
// parent: Object [@pragma pragma(String name, [Object? options])]
// parent: Comparable []
// parameter: T 99862877
// argument: num 235444537
// CONFIG
// config: num 1
// TYPE PATH:
//  num
// **************************************************************************
class $ObjectManager {
  $m1_Foo? _m1_Foo;
  $m1_Foo get m1_Foo {
    if (_m1_Foo == null) {
      _m1_Foo = new $m1_Foo();
    }
    return _m1_Foo as $m1_Foo;
  }

  $m1_FooChild? _m1_FooChild;
  $m1_FooChild get m1_FooChild {
    if (_m1_FooChild == null) {
      _m1_FooChild = new $m1_FooChild();
    }
    return _m1_FooChild as $m1_FooChild;
  }

  $m2_Foo? _m2_Foo;
  $m2_Foo get m2_Foo {
    if (_m2_Foo == null) {
      _m2_Foo = new $m2_Foo();
    }
    return _m2_Foo as $m2_Foo;
  }

  $generics_Param? _generics_Param;
  $generics_Param get generics_Param {
    if (_generics_Param == null) {
      _generics_Param = new $generics_Param();
    }
    return _generics_Param as $generics_Param;
  }

  $generics_SimpleSpecific? _generics_SimpleSpecific;
  $generics_SimpleSpecific get generics_SimpleSpecific {
    if (_generics_SimpleSpecific == null) {
      _generics_SimpleSpecific = new $generics_SimpleSpecific();
    }
    return _generics_SimpleSpecific as $generics_SimpleSpecific;
  }

  $generics_SimpleGeneric_generics_Param_?
      _generics_SimpleGeneric_generics_Param_;
  $generics_SimpleGeneric_generics_Param_
      get generics_SimpleGeneric_generics_Param_ {
    if (_generics_SimpleGeneric_generics_Param_ == null) {
      _generics_SimpleGeneric_generics_Param_ =
          new $generics_SimpleGeneric_generics_Param_();
    }
    return _generics_SimpleGeneric_generics_Param_
        as $generics_SimpleGeneric_generics_Param_;
  }

  $generics_SimpleGeneric_m1_Foo_? _generics_SimpleGeneric_m1_Foo_;
  $generics_SimpleGeneric_m1_Foo_ get generics_SimpleGeneric_m1_Foo_ {
    if (_generics_SimpleGeneric_m1_Foo_ == null) {
      _generics_SimpleGeneric_m1_Foo_ = new $generics_SimpleGeneric_m1_Foo_();
    }
    return _generics_SimpleGeneric_m1_Foo_ as $generics_SimpleGeneric_m1_Foo_;
  }

  $generics_SimpleGeneric_m2_Foo_? _generics_SimpleGeneric_m2_Foo_;
  $generics_SimpleGeneric_m2_Foo_ get generics_SimpleGeneric_m2_Foo_ {
    if (_generics_SimpleGeneric_m2_Foo_ == null) {
      _generics_SimpleGeneric_m2_Foo_ = new $generics_SimpleGeneric_m2_Foo_();
    }
    return _generics_SimpleGeneric_m2_Foo_ as $generics_SimpleGeneric_m2_Foo_;
  }
}

$ObjectManager $om = new $ObjectManager();
//generated in 8ms
