// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'factory.dart';

// **************************************************************************
// SwiftGenerator
// **************************************************************************

// **************************************************************************
// generated by swift_composer at 2022-02-13 19:49:20.557524
// config file for module_test: /home/fsw/workspace/swift_composer/test/lib/foo.di.yaml
// **************************************************************************
// ALL TYPES INFO
// **************************************************************************
// SubtypesOf => SubtypesOf  GENERIC [T = T   47246589 = 47246589   47246589 = TypeParameterTypeImpl]
// AnnotatedWith => AnnotatedWith   [      ]
// Pluggable => Pluggable   [      ]
// TypePlugin => TypePlugin  GENERIC [T = T   69357257 = 69357257   69357257 = TypeParameterTypeImpl]
// module_test.Foo => module_test.Foo INTERCEPTED  [      ]
// module_test.FooChild => module_test.FooChild INTERCEPTED  [      ]
// module_test.FooChild2 => module_test.FooChild2 INTERCEPTED  [      ]
// Complex => Complex INTERCEPTED  [      ]
// Container => Container INTERCEPTED  [      ]
// Object => Object   [      ]
// String => String   [T = String   459756122 = 153217077   459756122 = InterfaceTypeImpl]
// List<String> => List<String>   [T = E,E = String   194905962 = 40007411,40007411 = 153217077   194905962 = TypeParameterTypeImpl,40007411 = InterfaceTypeImpl]
// T => T   [      ]
// List<T> => List<T>   [T = E,E = T   194905962 = 40007411,40007411 = 47246589   194905962 = TypeParameterTypeImpl,40007411 = TypeParameterTypeImpl]
// dynamic => dynamic   [      ]
// ST => ST   [      ]
// int => int   [T = num   459756122 = 148975391   459756122 = InterfaceTypeImpl]
// double => double   [T = num   459756122 = 148975391   459756122 = InterfaceTypeImpl]
// bool => bool   [      ]
// void => void   [      ]
// **************************************************************************
// no interceptor for [SubtypesOf]
// type arguments[1]:
// T[47246589] => T[47246589]
// type arguments[2]:
// can be singleton: FALSE
// parameter: T 47246589
// argument: T 47246589
// parent: Object [@pragma pragma(String name, [Object? options])]
// CONFIG
// config: module_test.Foo {stringField: FooField, integerField: 124}
// config: module_test.FooChild {stringField: FooChildField, doubleField: 0.55, booleanField: true}
// config: module_test.FooChild2 {stringField: FooChild2Field, doubleField: 0.55, booleanField: true}
// config: SubtypesOf 1
// TYPE PATH:
//  SubtypesOf
// **************************************************************************
// no interceptor for [AnnotatedWith]
// type arguments[1]:
// type arguments[2]:
// can be singleton: FALSE
// parent: Object [@pragma pragma(String name, [Object? options])]
// CONFIG
// config: module_test.Foo {stringField: FooField, integerField: 124}
// config: module_test.FooChild {stringField: FooChildField, doubleField: 0.55, booleanField: true}
// config: module_test.FooChild2 {stringField: FooChild2Field, doubleField: 0.55, booleanField: true}
// config: AnnotatedWith 1
// TYPE PATH:
//  AnnotatedWith
// **************************************************************************
// no interceptor for [Pluggable]
// type arguments[1]:
// type arguments[2]:
// can be singleton: FALSE
// parent: Object [@pragma pragma(String name, [Object? options])]
// CONFIG
// config: module_test.Foo {stringField: FooField, integerField: 124}
// config: module_test.FooChild {stringField: FooChildField, doubleField: 0.55, booleanField: true}
// config: module_test.FooChild2 {stringField: FooChild2Field, doubleField: 0.55, booleanField: true}
// config: Pluggable 1
// TYPE PATH:
//  Pluggable
// **************************************************************************
// no interceptor for [TypePlugin]
// type arguments[1]:
// T[69357257] => T[69357257]
// type arguments[2]:
// can be singleton: FALSE
// parameter: T 69357257
// argument: T 69357257
// parent: Object [@pragma pragma(String name, [Object? options])]
// CONFIG
// config: module_test.Foo {stringField: FooField, integerField: 124}
// config: module_test.FooChild {stringField: FooChildField, doubleField: 0.55, booleanField: true}
// config: module_test.FooChild2 {stringField: FooChild2Field, doubleField: 0.55, booleanField: true}
// config: TypePlugin 1
// TYPE PATH:
//  TypePlugin
// **************************************************************************
// interceptor for [module_test.Foo]
// type arguments[1]:
// type arguments[2]:
// can be singleton: TRUE
// parent: Object [@pragma pragma(String name, [Object? options])]
// parent: Pluggable []
// CONFIG
// config: module_test.Foo {stringField: FooField, integerField: 124}
// config: module_test.FooChild {stringField: FooChildField, doubleField: 0.55, booleanField: true}
// config: module_test.FooChild2 {stringField: FooChild2Field, doubleField: 0.55, booleanField: true}
// config: module_test.Foo 1
// config: stringField FooField
// config: integerField 124
// TYPE PATH:
//  module_test.Foo
class $module_test_Foo extends module_test.Foo implements Pluggable {
  $module_test_Foo() {}
  T plugin<T>() {
    throw new Exception('no plugin for this type');
  }

// String className
// c: String
  String get className => "module_test.Foo";
// String stringField
// c: String
  String get stringField => "FooField";
// int integerField
// c: int
  int get integerField => 124;
}

// **************************************************************************
// interceptor for [module_test.FooChild]
// type arguments[1]:
// type arguments[2]:
// can be singleton: TRUE
// parent: Foo [@bool get Compose]
// parent: Object [@pragma pragma(String name, [Object? options])]
// parent: Pluggable []
// CONFIG
// config: module_test.Foo {stringField: FooField, integerField: 124}
// config: module_test.FooChild {stringField: FooChildField, doubleField: 0.55, booleanField: true}
// config: module_test.FooChild2 {stringField: FooChild2Field, doubleField: 0.55, booleanField: true}
// config: module_test.FooChild 1
// config: stringField FooChildField
// config: doubleField 0.55
// config: booleanField true
// config: module_test.Foo 2
// config: integerField 124
// TYPE PATH:
//  module_test.FooChild
//  module_test.Foo
class $module_test_FooChild extends module_test.FooChild implements Pluggable {
  $module_test_FooChild() {}
  T plugin<T>() {
    throw new Exception('no plugin for this type');
  }

// double doubleField
// c: double
  double get doubleField => 0.55;
// bool booleanField
// c: bool
  bool get booleanField => true;
// String className
// c: String
  String get className => "module_test.FooChild";
// String stringField
// c: String
  String get stringField => "FooChildField";
// int integerField
// c: int
  int get integerField => 124;
}

// **************************************************************************
// interceptor for [module_test.FooChild2]
// type arguments[1]:
// type arguments[2]:
// can be singleton: FALSE
// parent: Foo [@bool get Compose]
// parent: Object [@pragma pragma(String name, [Object? options])]
// parent: Pluggable []
// CONFIG
// config: module_test.Foo {stringField: FooField, integerField: 124}
// config: module_test.FooChild {stringField: FooChildField, doubleField: 0.55, booleanField: true}
// config: module_test.FooChild2 {stringField: FooChild2Field, doubleField: 0.55, booleanField: true}
// config: module_test.FooChild2 1
// config: stringField FooChild2Field
// config: doubleField 0.55
// config: booleanField true
// config: module_test.Foo 2
// config: integerField 124
// TYPE PATH:
//  module_test.FooChild2
//  module_test.Foo
class $module_test_FooChild2 extends module_test.FooChild2
    implements Pluggable {
  $module_test_FooChild2(requiredString) {
//String
    this.requiredString = requiredString;
  }
  T plugin<T>() {
    throw new Exception('no plugin for this type');
  }

// String requiredString
// c: String
// String className
// c: String
  String get className => "module_test.FooChild2";
// String stringField
// c: String
  String get stringField => "FooChild2Field";
// int integerField
// c: int
  int get integerField => 124;
}

// **************************************************************************
// interceptor for [Complex]
// type arguments[1]:
// type arguments[2]:
// can be singleton: FALSE
// parent: Object [@pragma pragma(String name, [Object? options])]
// CONFIG
// config: module_test.Foo {stringField: FooField, integerField: 124}
// config: module_test.FooChild {stringField: FooChildField, doubleField: 0.55, booleanField: true}
// config: module_test.FooChild2 {stringField: FooChild2Field, doubleField: 0.55, booleanField: true}
// config: Complex 1
// TYPE PATH:
//  Complex
class $Complex extends Complex implements Pluggable {
  $Complex(requiredString, requiredFoo) {
//String
    this.requiredString = requiredString;
//Foo
    this.requiredFoo = requiredFoo;
  }
  T plugin<T>() {
    throw new Exception('no plugin for this type');
  }
// String requiredString
// c: String
// module_test.Foo requiredFoo
// c: module_test.Foo
// c: module_test.FooChild
// c: module_test.FooChild2
}

// **************************************************************************
// interceptor for [Container]
// type arguments[1]:
// type arguments[2]:
// can be singleton: TRUE
// parent: Object [@pragma pragma(String name, [Object? options])]
// CONFIG
// config: module_test.Foo {stringField: FooField, integerField: 124}
// config: module_test.FooChild {stringField: FooChildField, doubleField: 0.55, booleanField: true}
// config: module_test.FooChild2 {stringField: FooChild2Field, doubleField: 0.55, booleanField: true}
// config: Container 1
// TYPE PATH:
//  Container
class $Container extends Container implements Pluggable {
  $Container() {}
  T plugin<T>() {
    throw new Exception('no plugin for this type');
  }

  module_test.Foo createFoo() {
//module_test.Foo
    return new $module_test_Foo();
  }

  Complex createComplex(String requiredString, module_test.Foo requiredFoo) {
//Complex
    return new $Complex(requiredString, requiredFoo);
  }

  module_test.Foo createSubFoo(String className) {
    switch (className) {
      case 'module_test.Foo':
        return new $module_test_Foo();
      case 'module_test.FooChild':
        return new $module_test_FooChild();
    }
    throw new Exception('no type for ' + className);
  }
}

// **************************************************************************
// no interceptor for [Object]
// type arguments[1]:
// type arguments[2]:
// can be singleton: FALSE
// CONFIG
// config: module_test.Foo {stringField: FooField, integerField: 124}
// config: module_test.FooChild {stringField: FooChildField, doubleField: 0.55, booleanField: true}
// config: module_test.FooChild2 {stringField: FooChild2Field, doubleField: 0.55, booleanField: true}
// config: Object 1
// TYPE PATH:
//  Object
// **************************************************************************
// no interceptor for [String]
// type arguments[1]:
// T[459756122] => String[153217077]
// type arguments[2]:
// can be singleton: FALSE
// parent: Object [@pragma pragma(String name, [Object? options])]
// parent: Comparable []
// parameter: T 459756122
// argument: String 153217077
// parent: Pattern []
// CONFIG
// config: module_test.Foo {stringField: FooField, integerField: 124}
// config: module_test.FooChild {stringField: FooChildField, doubleField: 0.55, booleanField: true}
// config: module_test.FooChild2 {stringField: FooChild2Field, doubleField: 0.55, booleanField: true}
// config: String 1
// TYPE PATH:
//  String
// **************************************************************************
// no interceptor for [List<String>]
// type arguments[1]:
// T[194905962] => E[40007411]
// E[37912016] => E[40007411]
// E[40007411] => String[153217077]
// type arguments[2]:
// ENCLOSING: XXX
// String[87950495]
// can be singleton: FALSE
// parameter: E 40007411
// argument: E 40007411
// parent: Object [@pragma pragma(String name, [Object? options])]
// parent: EfficientLengthIterable []
// parameter: T 194905962
// argument: E 40007411
// parent: Iterable []
// parameter: E 37912016
// argument: E 40007411
// CONFIG
// config: module_test.Foo {stringField: FooField, integerField: 124}
// config: module_test.FooChild {stringField: FooChildField, doubleField: 0.55, booleanField: true}
// config: module_test.FooChild2 {stringField: FooChild2Field, doubleField: 0.55, booleanField: true}
// config: List 1
// TYPE PATH:
//  List
// **************************************************************************
// no interceptor for [T]
// type arguments[1]:
// type arguments[2]:
// **************************************************************************
// no interceptor for [List<T>]
// type arguments[1]:
// T[194905962] => E[40007411]
// E[37912016] => E[40007411]
// E[40007411] => T[47246589]
// type arguments[2]:
// ENCLOSING: NULL
// T[542296175]
// can be singleton: FALSE
// parameter: E 40007411
// argument: E 40007411
// parent: Object [@pragma pragma(String name, [Object? options])]
// parent: EfficientLengthIterable []
// parameter: T 194905962
// argument: E 40007411
// parent: Iterable []
// parameter: E 37912016
// argument: E 40007411
// CONFIG
// config: module_test.Foo {stringField: FooField, integerField: 124}
// config: module_test.FooChild {stringField: FooChildField, doubleField: 0.55, booleanField: true}
// config: module_test.FooChild2 {stringField: FooChild2Field, doubleField: 0.55, booleanField: true}
// config: List 1
// TYPE PATH:
//  List
// **************************************************************************
// no interceptor for [dynamic]
// type arguments[1]:
// type arguments[2]:
// **************************************************************************
// no interceptor for [ST]
// type arguments[1]:
// type arguments[2]:
// **************************************************************************
// no interceptor for [int]
// type arguments[1]:
// T[459756122] => num[148975391]
// type arguments[2]:
// can be singleton: FALSE
// parent: num []
// parent: Object [@pragma pragma(String name, [Object? options])]
// parent: Comparable []
// parameter: T 459756122
// argument: num 148975391
// CONFIG
// config: module_test.Foo {stringField: FooField, integerField: 124}
// config: module_test.FooChild {stringField: FooChildField, doubleField: 0.55, booleanField: true}
// config: module_test.FooChild2 {stringField: FooChild2Field, doubleField: 0.55, booleanField: true}
// config: int 1
// config: num 2
// TYPE PATH:
//  int
//  num
// **************************************************************************
// no interceptor for [double]
// type arguments[1]:
// T[459756122] => num[148975391]
// type arguments[2]:
// can be singleton: FALSE
// parent: num []
// parent: Object [@pragma pragma(String name, [Object? options])]
// parent: Comparable []
// parameter: T 459756122
// argument: num 148975391
// CONFIG
// config: module_test.Foo {stringField: FooField, integerField: 124}
// config: module_test.FooChild {stringField: FooChildField, doubleField: 0.55, booleanField: true}
// config: module_test.FooChild2 {stringField: FooChild2Field, doubleField: 0.55, booleanField: true}
// config: double 1
// config: num 2
// TYPE PATH:
//  double
//  num
// **************************************************************************
// no interceptor for [bool]
// type arguments[1]:
// type arguments[2]:
// can be singleton: FALSE
// parent: Object [@pragma pragma(String name, [Object? options])]
// CONFIG
// config: module_test.Foo {stringField: FooField, integerField: 124}
// config: module_test.FooChild {stringField: FooChildField, doubleField: 0.55, booleanField: true}
// config: module_test.FooChild2 {stringField: FooChild2Field, doubleField: 0.55, booleanField: true}
// config: bool 1
// TYPE PATH:
//  bool
// **************************************************************************
// no interceptor for [void]
// type arguments[1]:
// type arguments[2]:
// **************************************************************************
// no interceptor for [SubtypesOf<T>]
// type arguments[1]:
// T[47246589] => T[47246589]
// type arguments[2]:
// ENCLOSING: NULL
// T[542296175]
// can be singleton: FALSE
// parameter: T 47246589
// argument: T 47246589
// parent: Object [@pragma pragma(String name, [Object? options])]
// CONFIG
// config: module_test.Foo {stringField: FooField, integerField: 124}
// config: module_test.FooChild {stringField: FooChildField, doubleField: 0.55, booleanField: true}
// config: module_test.FooChild2 {stringField: FooChild2Field, doubleField: 0.55, booleanField: true}
// config: SubtypesOf 1
// TYPE PATH:
//  SubtypesOf
// **************************************************************************
// no interceptor for [TypePlugin<T>]
// type arguments[1]:
// T[69357257] => T[69357257]
// type arguments[2]:
// ENCLOSING: NULL
// T[542296175]
// can be singleton: FALSE
// parameter: T 69357257
// argument: T 69357257
// parent: Object [@pragma pragma(String name, [Object? options])]
// CONFIG
// config: module_test.Foo {stringField: FooField, integerField: 124}
// config: module_test.FooChild {stringField: FooChildField, doubleField: 0.55, booleanField: true}
// config: module_test.FooChild2 {stringField: FooChild2Field, doubleField: 0.55, booleanField: true}
// config: TypePlugin 1
// TYPE PATH:
//  TypePlugin
// **************************************************************************
// no interceptor for [num]
// type arguments[1]:
// T[459756122] => num[148975391]
// type arguments[2]:
// can be singleton: FALSE
// parent: Object [@pragma pragma(String name, [Object? options])]
// parent: Comparable []
// parameter: T 459756122
// argument: num 148975391
// CONFIG
// config: module_test.Foo {stringField: FooField, integerField: 124}
// config: module_test.FooChild {stringField: FooChildField, doubleField: 0.55, booleanField: true}
// config: module_test.FooChild2 {stringField: FooChild2Field, doubleField: 0.55, booleanField: true}
// config: num 1
// TYPE PATH:
//  num
// **************************************************************************
class $ObjectManager {
  $module_test_Foo? _module_test_Foo;
  $module_test_Foo get module_test_Foo {
    if (_module_test_Foo == null) {
      _module_test_Foo = new $module_test_Foo();
    }
    return _module_test_Foo as $module_test_Foo;
  }

  $module_test_FooChild? _module_test_FooChild;
  $module_test_FooChild get module_test_FooChild {
    if (_module_test_FooChild == null) {
      _module_test_FooChild = new $module_test_FooChild();
    }
    return _module_test_FooChild as $module_test_FooChild;
  }

  $Container? _container;
  $Container get container {
    if (_container == null) {
      _container = new $Container();
    }
    return _container as $Container;
  }
}

$ObjectManager $om = new $ObjectManager();
//generated in 4ms
