// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'plugins.dart';

// **************************************************************************
// SwiftGenerator
// **************************************************************************

// **************************************************************************
// generated by swift_composer at 2022-09-04 12:20:41.243989
// **************************************************************************
// CONFIG
// no config file for root: /home/fsw/workspace/swift_shop/packages/swift_composer/.dart_tool/..//lib/swift_composer.di.yaml
// config file for foo: /home/fsw/workspace/swift_shop/packages/swift_composer/test/plugins/../lib/foo.di.yaml
// config file for bar: /home/fsw/workspace/swift_shop/packages/swift_composer/test/plugins/../lib/bar.di.yaml
// no config file for generics: /home/fsw/workspace/swift_shop/packages/swift_composer/test/plugins/../lib/generics.di.yaml
// no config file for root: /home/fsw/workspace/swift_shop/packages/swift_composer/test/plugins/plugins.di.yaml
// **************************************************************************
// MERGED CONFIG
// foo.Foo: {stringField: FooField, integerField: 124}
// foo.FooChild: {stringField: FooChildField, doubleField: 0.55, booleanField: true}
// foo.FooChild2: {stringField: FooChild2Field, doubleField: 0.55, booleanField: true}
// bar.Bar: {stringField: BarStringField}
// bar.BarChild: {stringField: BarChildStringField}
// **************************************************************************
// ALL TYPES INFO
// **************************************************************************
// SubtypesOf => SubtypesOf  GENERIC [T = T   473656069 = 473656069   473656069 = TypeParameterTypeImpl]
// AnnotatedWith => AnnotatedWith   [      ]
// Pluggable => Pluggable   [      ]
// TypePlugin => TypePlugin  GENERIC [T = T   380287154 = 380287154   380287154 = TypeParameterTypeImpl]
// foo.Foo => foo.Foo INTERCEPTED  [      ]
// foo.FooChild => foo.FooChild INTERCEPTED  [      ]
// foo.FooChild2 => foo.FooChild2 INTERCEPTED  [      ]
// bar.Bar => bar.Bar INTERCEPTED  [      ]
// bar.BarChild => bar.BarChild INTERCEPTED  [      ]
// generics.SimpleGeneric => generics.SimpleGeneric  GENERIC [T = T   516375725 = 516375725   516375725 = TypeParameterTypeImpl]
// generics.Param => generics.Param INTERCEPTED  [      ]
// generics.SimpleSpecific => generics.SimpleSpecific INTERCEPTED  [T = Param   516375725 = 356184557   516375725 = InterfaceTypeImpl]
// generics.ComplexGeneric => generics.ComplexGeneric  GENERIC [A = A,B = B   99844900 = 99844900,364591990 = 364591990   99844900 = TypeParameterTypeImpl,364591990 = TypeParameterTypeImpl]
// generics.SuperComplexGeneric => generics.SuperComplexGeneric  GENERIC [A = A,B = B   517102781 = 517102781,258296657 = 258296657   517102781 = TypeParameterTypeImpl,258296657 = TypeParameterTypeImpl]
// SimplePlugin => SimplePlugin INTERCEPTED  [T = Foo   380287154 = 4632883   380287154 = InterfaceTypeImpl]
// MoreComplexPlugin => MoreComplexPlugin INTERCEPTED  [T = Foo   380287154 = 4632883   380287154 = InterfaceTypeImpl]
// PluginOnGeneric => PluginOnGeneric INTERCEPTED  [T = SimpleGeneric<dynamic>   380287154 = 179991359   380287154 = InterfaceTypeImpl]
// AbstractGeneric => AbstractGeneric  GENERIC [T = T   86505154 = 86505154   86505154 = TypeParameterTypeImpl]
// GenericTypedWithFoo => GenericTypedWithFoo INTERCEPTED  [T = Foo   86505154 = 4632883   86505154 = InterfaceTypeImpl]
// GenericContainer => GenericContainer  GENERIC [T = T   462569427 = 462569427   462569427 = TypeParameterTypeImpl]
// ContainerFoo => ContainerFoo INTERCEPTED  [T = Foo   462569427 = 4632883   462569427 = InterfaceTypeImpl]
// Object => Object   [      ]
// String => String   [T = String   99862877 = 55285317   99862877 = InterfaceTypeImpl]
// List<String> => List<String>   [T = E,E = String   265238202 = 263610483,263610483 = 55285317   265238202 = TypeParameterTypeImpl,263610483 = InterfaceTypeImpl]
// T => T   [      ]
// List<T> => List<T>   [T = E,E = T   265238202 = 263610483,263610483 = 473656069   265238202 = TypeParameterTypeImpl,263610483 = TypeParameterTypeImpl]
// dynamic => dynamic   [      ]
// ST => ST   [      ]
// int => int   [T = num   99862877 = 235444537   99862877 = InterfaceTypeImpl]
// double => double   [T = num   99862877 = 235444537   99862877 = InterfaceTypeImpl]
// bool => bool   [      ]
// void => void   [      ]
// generics.SimpleGeneric<generics.Param> => generics.SimpleGeneric<generics.Param> INTERCEPTED  [T = Param   516375725 = 356184557   516375725 = InterfaceTypeImpl]
// A => A   [      ]
// B => B   [      ]
// generics.ComplexGeneric<generics.Param,A> => generics.ComplexGeneric<generics.Param,A>   [A = Param,B = A   99844900 = 356184557,364591990 = 517102781   99844900 = InterfaceTypeImpl,364591990 = TypeParameterTypeImpl]
// TypePlugin<foo.Foo> => TypePlugin<foo.Foo>   [T = Foo   380287154 = 4632883   380287154 = InterfaceTypeImpl]
// List<dynamic> => List<dynamic>   [T = E,E = dynamic   265238202 = 263610483,263610483 = 1   265238202 = TypeParameterTypeImpl,263610483 = DynamicTypeImpl]
// generics.SimpleGeneric<dynamic> => generics.SimpleGeneric<dynamic>   [T = dynamic   516375725 = 1   516375725 = DynamicTypeImpl]
// TypePlugin<generics.SimpleGeneric<dynamic>> => TypePlugin<generics.SimpleGeneric<dynamic>>   [T = SimpleGeneric<dynamic>   380287154 = 179991359   380287154 = InterfaceTypeImpl]
// generics.SimpleGeneric<T> => generics.SimpleGeneric<T>   [T = T   516375725 = 86505154   516375725 = TypeParameterTypeImpl]
// AbstractGeneric<foo.Foo> => AbstractGeneric<foo.Foo> INTERCEPTED  [T = Foo   86505154 = 4632883   86505154 = InterfaceTypeImpl]
// generics.SimpleGeneric<foo.Foo> => generics.SimpleGeneric<foo.Foo> INTERCEPTED  [T = T   516375725 = 86505154   516375725 = TypeParameterTypeImpl]
// AbstractGeneric<T> => AbstractGeneric<T>   [T = T   86505154 = 462569427   86505154 = TypeParameterTypeImpl]
// GenericContainer<foo.Foo> => GenericContainer<foo.Foo>   [T = Foo   462569427 = 4632883   462569427 = InterfaceTypeImpl]
// **************************************************************************
// no interceptor for [SubtypesOf]
// type arguments[1]:
// T[473656069] => T[473656069]
// type arguments[2]:
// can be singleton: FALSE
// parameter: T 473656069
// argument: T 473656069
// parent: Object [@pragma pragma(String name, [Object? options])]
// CONFIG
// config: SubtypesOf 1
// TYPE PATH:
//  SubtypesOf
// **************************************************************************
// no interceptor for [AnnotatedWith]
// type arguments[1]:
// type arguments[2]:
// can be singleton: FALSE
// parent: Object [@pragma pragma(String name, [Object? options])]
// CONFIG
// config: AnnotatedWith 1
// TYPE PATH:
//  AnnotatedWith
// **************************************************************************
// no interceptor for [Pluggable]
// type arguments[1]:
// type arguments[2]:
// can be singleton: FALSE
// parent: Object [@pragma pragma(String name, [Object? options])]
// CONFIG
// config: Pluggable 1
// TYPE PATH:
//  Pluggable
// **************************************************************************
// no interceptor for [TypePlugin]
// type arguments[1]:
// T[380287154] => T[380287154]
// type arguments[2]:
// can be singleton: FALSE
// parameter: T 380287154
// argument: T 380287154
// parent: Object [@pragma pragma(String name, [Object? options])]
// CONFIG
// config: TypePlugin 1
// TYPE PATH:
//  TypePlugin
// **************************************************************************
// interceptor for [foo.Foo]
// type arguments[1]:
// type arguments[2]:
// can be singleton: TRUE
// parent: Object [@pragma pragma(String name, [Object? options])]
// parent: Pluggable []
// plugin: SimplePlugin
// plugin: MoreComplexPlugin
// CONFIG
// config: foo.Foo 1
// config: stringField FooField
// config: integerField 124
// TYPE PATH:
//  foo.Foo
class $foo_Foo extends foo.Foo implements Pluggable {
  late SimplePlugin simplePlugin;
  late MoreComplexPlugin moreComplexPlugin;
  $foo_Foo() {
    simplePlugin = new $SimplePlugin(this);
    moreComplexPlugin = new $MoreComplexPlugin(this);
  }
  T plugin<T>() {
    if (T == SimplePlugin) {
      return simplePlugin as T;
    }
    if (T == MoreComplexPlugin) {
      return moreComplexPlugin as T;
    }
    throw new Exception('no plugin for this type');
  }

// String className
// c: String
  String get className => "foo.Foo";
// String stringField
// c: String
  String get stringField => "FooField";
// int integerField
// c: int
  int get integerField => 124;
//method format override
  String format(String prefix) {
    List<dynamic> args = [prefix];
    args = simplePlugin.beforeFormat(args[0]);
    prefix = args[0];
    var ret = super.format(prefix);
    ret = simplePlugin.afterFormat(ret);
    return ret;
  }
}

// **************************************************************************
// interceptor for [foo.FooChild]
// type arguments[1]:
// type arguments[2]:
// can be singleton: TRUE
// parent: Foo [@bool get Compose]
// parent: Object [@pragma pragma(String name, [Object? options])]
// parent: Pluggable []
// plugin: SimplePlugin
// plugin: MoreComplexPlugin
// CONFIG
// config: foo.FooChild 1
// config: stringField FooChildField
// config: doubleField 0.55
// config: booleanField true
// config: foo.Foo 2
// config: integerField 124
// TYPE PATH:
//  foo.FooChild
//  foo.Foo
class $foo_FooChild extends foo.FooChild implements Pluggable {
  late SimplePlugin simplePlugin;
  late MoreComplexPlugin moreComplexPlugin;
  $foo_FooChild() {
    simplePlugin = new $SimplePlugin(this);
    moreComplexPlugin = new $MoreComplexPlugin(this);
  }
  T plugin<T>() {
    if (T == SimplePlugin) {
      return simplePlugin as T;
    }
    if (T == MoreComplexPlugin) {
      return moreComplexPlugin as T;
    }
    throw new Exception('no plugin for this type');
  }

// double doubleField
// c: double
  double get doubleField => 0.55;
// bool booleanField
// c: bool
  bool get booleanField => true;
// String className
// c: String
  String get className => "foo.FooChild";
// String stringField
// c: String
  String get stringField => "FooChildField";
// int integerField
// c: int
  int get integerField => 124;
//method format override
  String format(String prefix) {
    List<dynamic> args = [prefix];
    args = simplePlugin.beforeFormat(args[0]);
    prefix = args[0];
    var ret = super.format(prefix);
    ret = simplePlugin.afterFormat(ret);
    return ret;
  }
}

// **************************************************************************
// interceptor for [foo.FooChild2]
// type arguments[1]:
// type arguments[2]:
// can be singleton: FALSE
// parent: Foo [@bool get Compose]
// parent: Object [@pragma pragma(String name, [Object? options])]
// parent: Pluggable []
// plugin: SimplePlugin
// plugin: MoreComplexPlugin
// CONFIG
// config: foo.FooChild2 1
// config: stringField FooChild2Field
// config: doubleField 0.55
// config: booleanField true
// config: foo.Foo 2
// config: integerField 124
// TYPE PATH:
//  foo.FooChild2
//  foo.Foo
class $foo_FooChild2 extends foo.FooChild2 implements Pluggable {
  late SimplePlugin simplePlugin;
  late MoreComplexPlugin moreComplexPlugin;
  $foo_FooChild2(requiredString) {
//String
    this.requiredString = requiredString;
    simplePlugin = new $SimplePlugin(this);
    moreComplexPlugin = new $MoreComplexPlugin(this);
  }
  T plugin<T>() {
    if (T == SimplePlugin) {
      return simplePlugin as T;
    }
    if (T == MoreComplexPlugin) {
      return moreComplexPlugin as T;
    }
    throw new Exception('no plugin for this type');
  }

// String requiredString
// c: String
// String className
// c: String
  String get className => "foo.FooChild2";
// String stringField
// c: String
  String get stringField => "FooChild2Field";
// int integerField
// c: int
  int get integerField => 124;
//method format override
  String format(String prefix) {
    List<dynamic> args = [prefix];
    args = simplePlugin.beforeFormat(args[0]);
    prefix = args[0];
    var ret = super.format(prefix);
    ret = simplePlugin.afterFormat(ret);
    return ret;
  }
}

// **************************************************************************
// interceptor for [bar.Bar]
// type arguments[1]:
// type arguments[2]:
// can be singleton: TRUE
// parent: Object [@pragma pragma(String name, [Object? options])]
// CONFIG
// config: bar.Bar 1
// config: stringField BarStringField
// TYPE PATH:
//  bar.Bar
class $bar_Bar extends bar.Bar implements Pluggable {
  $bar_Bar() {}
  T plugin<T>() {
    throw new Exception('no plugin for this type');
  }

// List<String> classNames
// c: List<String>
  List<String> get classNames => [];
// String stringField
// c: String
  String get stringField => "BarStringField";
}

// **************************************************************************
// interceptor for [bar.BarChild]
// type arguments[1]:
// type arguments[2]:
// can be singleton: TRUE
// parent: Bar [@bool get Compose]
// parent: Object [@pragma pragma(String name, [Object? options])]
// CONFIG
// config: bar.BarChild 1
// config: stringField BarChildStringField
// config: bar.Bar 2
// TYPE PATH:
//  bar.BarChild
//  bar.Bar
class $bar_BarChild extends bar.BarChild implements Pluggable {
  $bar_BarChild() {}
  T plugin<T>() {
    throw new Exception('no plugin for this type');
  }

// List<String> classNames
// c: List<String>
  List<String> get classNames => ['bar.BarChild'];
// String stringField
// c: String
  String get stringField => "BarChildStringField";
}

// **************************************************************************
// no interceptor for [generics.SimpleGeneric]
// type arguments[1]:
// T[516375725] => T[516375725]
// type arguments[2]:
// can be singleton: FALSE
// parameter: T 516375725
// argument: T 516375725
// parent: Object [@pragma pragma(String name, [Object? options])]
// parent: Pluggable []
// plugin: PluginOnGeneric
// CONFIG
// config: generics.SimpleGeneric 1
// TYPE PATH:
//  generics.SimpleGeneric
// **************************************************************************
// interceptor for [generics.Param]
// type arguments[1]:
// type arguments[2]:
// can be singleton: TRUE
// parent: Object [@pragma pragma(String name, [Object? options])]
// CONFIG
// config: generics.Param 1
// TYPE PATH:
//  generics.Param
class $generics_Param extends generics.Param implements Pluggable {
  $generics_Param() {}
  T plugin<T>() {
    throw new Exception('no plugin for this type');
  }
}

// **************************************************************************
// interceptor for [generics.SimpleSpecific]
// type arguments[1]:
// T[516375725] => Param[356184557]
// type arguments[2]:
// can be singleton: TRUE
// parent: SimpleGeneric [@bool get Compose]
// parameter: T 516375725
// argument: Param 356184557
// parent: Object [@pragma pragma(String name, [Object? options])]
// parent: Pluggable []
// plugin: PluginOnGeneric
// CONFIG
// config: generics.SimpleSpecific 1
// config: generics.SimpleGeneric 2
// TYPE PATH:
//  generics.SimpleSpecific
//  generics.SimpleGeneric
class $generics_SimpleSpecific extends generics.SimpleSpecific
    implements Pluggable {
  late PluginOnGeneric pluginOnGeneric;
  $generics_SimpleSpecific() {
    pluginOnGeneric = new $PluginOnGeneric(this);
  }
  T plugin<T>() {
    if (T == PluginOnGeneric) {
      return pluginOnGeneric as T;
    }
    throw new Exception('no plugin for this type');
  }
}

// **************************************************************************
// no interceptor for [generics.ComplexGeneric]
// type arguments[1]:
// A[99844900] => A[99844900]
// B[364591990] => B[364591990]
// type arguments[2]:
// can be singleton: FALSE
// parameter: A 99844900
// parameter: B 364591990
// argument: A 99844900
// argument: B 364591990
// parent: Object [@pragma pragma(String name, [Object? options])]
// CONFIG
// config: generics.ComplexGeneric 1
// TYPE PATH:
//  generics.ComplexGeneric
// **************************************************************************
// no interceptor for [generics.SuperComplexGeneric]
// type arguments[1]:
// A[99844900] => Param[356184557]
// B[364591990] => A[517102781]
// A[517102781] => A[517102781]
// B[258296657] => B[258296657]
// type arguments[2]:
// can be singleton: FALSE
// parameter: A 517102781
// parameter: B 258296657
// argument: A 517102781
// argument: B 258296657
// parent: ComplexGeneric [@bool get Compose]
// parameter: A 99844900
// parameter: B 364591990
// argument: Param 356184557
// argument: A 517102781
// parent: Object [@pragma pragma(String name, [Object? options])]
// CONFIG
// config: generics.SuperComplexGeneric 1
// config: generics.ComplexGeneric 2
// TYPE PATH:
//  generics.SuperComplexGeneric
//  generics.ComplexGeneric
// **************************************************************************
// interceptor for [SimplePlugin]
// type arguments[1]:
// T[380287154] => Foo[4632883]
// type arguments[2]:
// can be singleton: FALSE
// parent: TypePlugin [@bool get ComposeSubtypes]
// parameter: T 380287154
// argument: Foo 4632883
// parent: Object [@pragma pragma(String name, [Object? options])]
// CONFIG
// config: SimplePlugin 1
// config: TypePlugin 2
// TYPE PATH:
//  SimplePlugin
//  TypePlugin
class $SimplePlugin extends SimplePlugin implements Pluggable {
  $SimplePlugin(parent) {
//T
    this.parent = parent;
  }
  T plugin<T>() {
    throw new Exception('no plugin for this type');
  }
// foo.Foo parent
// c: foo.Foo
// c: foo.FooChild
// c: foo.FooChild2
}

// **************************************************************************
// interceptor for [MoreComplexPlugin]
// type arguments[1]:
// T[380287154] => Foo[4632883]
// type arguments[2]:
// can be singleton: FALSE
// parent: TypePlugin [@bool get ComposeSubtypes]
// parameter: T 380287154
// argument: Foo 4632883
// parent: Object [@pragma pragma(String name, [Object? options])]
// CONFIG
// config: MoreComplexPlugin 1
// config: TypePlugin 2
// TYPE PATH:
//  MoreComplexPlugin
//  TypePlugin
class $MoreComplexPlugin extends MoreComplexPlugin implements Pluggable {
  $MoreComplexPlugin(parent) {
//T
    this.parent = parent;
  }
  T plugin<T>() {
    throw new Exception('no plugin for this type');
  }

// bar.Bar barField
// c: bar.Bar
// c: bar.BarChild
  bar.Bar get barField => $om.bar_Bar;
// foo.Foo parent
// c: foo.Foo
// c: foo.FooChild
// c: foo.FooChild2
}

// **************************************************************************
// interceptor for [PluginOnGeneric]
// type arguments[1]:
// T[380287154] => SimpleGeneric<dynamic>[179991359]
// type arguments[2]:
// can be singleton: FALSE
// parent: TypePlugin [@bool get ComposeSubtypes]
// parameter: T 380287154
// argument: SimpleGeneric 179991359
// parent: Object [@pragma pragma(String name, [Object? options])]
// CONFIG
// config: PluginOnGeneric 1
// config: TypePlugin 2
// TYPE PATH:
//  PluginOnGeneric
//  TypePlugin
class $PluginOnGeneric extends PluginOnGeneric implements Pluggable {
  $PluginOnGeneric(parent) {
//T
    this.parent = parent;
  }
  T plugin<T>() {
    throw new Exception('no plugin for this type');
  }

// bar.Bar barField
// c: bar.Bar
// c: bar.BarChild
  bar.Bar get barField => $om.bar_Bar;
// generics.SimpleGeneric parent
// c: generics.SimpleGeneric
}

// **************************************************************************
// no interceptor for [AbstractGeneric]
// type arguments[1]:
// T[86505154] => T[86505154]
// type arguments[2]:
// can be singleton: FALSE
// parameter: T 86505154
// argument: T 86505154
// parent: Object [@pragma pragma(String name, [Object? options])]
// CONFIG
// config: AbstractGeneric 1
// TYPE PATH:
//  AbstractGeneric
// **************************************************************************
// interceptor for [GenericTypedWithFoo]
// type arguments[1]:
// T[86505154] => Foo[4632883]
// type arguments[2]:
// can be singleton: TRUE
// parent: AbstractGeneric [@bool get Compose]
// parameter: T 86505154
// argument: Foo 4632883
// parent: Object [@pragma pragma(String name, [Object? options])]
// CONFIG
// config: GenericTypedWithFoo 1
// config: AbstractGeneric 2
// TYPE PATH:
//  GenericTypedWithFoo
//  AbstractGeneric
class $GenericTypedWithFoo extends GenericTypedWithFoo implements Pluggable {
  $GenericTypedWithFoo() {}
  T plugin<T>() {
    throw new Exception('no plugin for this type');
  }

// foo.Foo element
// c: foo.Foo
// c: foo.FooChild
// c: foo.FooChild2
  foo.Foo get element => $om.foo_Foo;
// generics.SimpleGeneric<foo.Foo> generic
// c: generics.SimpleGeneric<foo.Foo>
  generics.SimpleGeneric<foo.Foo> get generic =>
      $om.generics_SimpleGeneric_foo_Foo_;
}

// **************************************************************************
// no interceptor for [GenericContainer]
// type arguments[1]:
// T[462569427] => T[462569427]
// type arguments[2]:
// can be singleton: FALSE
// parameter: T 462569427
// argument: T 462569427
// parent: Object [@pragma pragma(String name, [Object? options])]
// CONFIG
// config: GenericContainer 1
// TYPE PATH:
//  GenericContainer
// **************************************************************************
// interceptor for [ContainerFoo]
// type arguments[1]:
// T[462569427] => Foo[4632883]
// type arguments[2]:
// can be singleton: TRUE
// parent: GenericContainer []
// parameter: T 462569427
// argument: Foo 4632883
// parent: Object [@pragma pragma(String name, [Object? options])]
// CONFIG
// config: ContainerFoo 1
// config: GenericContainer 2
// TYPE PATH:
//  ContainerFoo
//  GenericContainer
class $ContainerFoo extends ContainerFoo implements Pluggable {
  $ContainerFoo() {
//AbstractGeneric<T>
//create
//AbstractGeneric<foo.Foo>
// c: GenericTypedWithFoo
// c: AbstractGeneric<foo.Foo>
    this.genericFoo = new $AbstractGeneric_foo_Foo_();
//T
//create
//foo.Foo
// c: foo.Foo
// c: foo.FooChild
// c: foo.FooChild2
    this.child = new $foo_Foo();
  }
  T plugin<T>() {
    throw new Exception('no plugin for this type');
  }
// AbstractGeneric<foo.Foo> genericFoo
// c: GenericTypedWithFoo
// c: AbstractGeneric<foo.Foo>
// foo.Foo child
// c: foo.Foo
// c: foo.FooChild
// c: foo.FooChild2
}

// **************************************************************************
// no interceptor for [Object]
// type arguments[1]:
// type arguments[2]:
// can be singleton: FALSE
// CONFIG
// config: Object 1
// TYPE PATH:
//  Object
// **************************************************************************
// no interceptor for [String]
// type arguments[1]:
// T[99862877] => String[55285317]
// type arguments[2]:
// can be singleton: FALSE
// parent: Object [@pragma pragma(String name, [Object? options])]
// parent: Comparable []
// parameter: T 99862877
// argument: String 55285317
// parent: Pattern []
// CONFIG
// config: String 1
// TYPE PATH:
//  String
// **************************************************************************
// no interceptor for [List<String>]
// type arguments[1]:
// T[265238202] => E[263610483]
// E[268730869] => E[263610483]
// E[263610483] => String[55285317]
// type arguments[2]:
// ENCLOSING: XXX
// String[619022460]
// can be singleton: FALSE
// parameter: E 263610483
// argument: E 263610483
// parent: Object [@pragma pragma(String name, [Object? options])]
// parent: EfficientLengthIterable []
// parameter: T 265238202
// argument: E 263610483
// parent: Iterable []
// parameter: E 268730869
// argument: E 263610483
// CONFIG
// config: List 1
// TYPE PATH:
//  List
// **************************************************************************
// no interceptor for [T]
// type arguments[1]:
// type arguments[2]:
// **************************************************************************
// no interceptor for [List<T>]
// type arguments[1]:
// T[265238202] => E[263610483]
// E[268730869] => E[263610483]
// E[263610483] => T[473656069]
// type arguments[2]:
// ENCLOSING: NULL
// T[922847711]
// can be singleton: FALSE
// parameter: E 263610483
// argument: E 263610483
// parent: Object [@pragma pragma(String name, [Object? options])]
// parent: EfficientLengthIterable []
// parameter: T 265238202
// argument: E 263610483
// parent: Iterable []
// parameter: E 268730869
// argument: E 263610483
// CONFIG
// config: List 1
// TYPE PATH:
//  List
// **************************************************************************
// no interceptor for [dynamic]
// type arguments[1]:
// type arguments[2]:
// **************************************************************************
// no interceptor for [ST]
// type arguments[1]:
// type arguments[2]:
// **************************************************************************
// no interceptor for [int]
// type arguments[1]:
// T[99862877] => num[235444537]
// type arguments[2]:
// can be singleton: FALSE
// parent: num []
// parent: Object [@pragma pragma(String name, [Object? options])]
// parent: Comparable []
// parameter: T 99862877
// argument: num 235444537
// CONFIG
// config: int 1
// config: num 2
// TYPE PATH:
//  int
//  num
// **************************************************************************
// no interceptor for [double]
// type arguments[1]:
// T[99862877] => num[235444537]
// type arguments[2]:
// can be singleton: FALSE
// parent: num []
// parent: Object [@pragma pragma(String name, [Object? options])]
// parent: Comparable []
// parameter: T 99862877
// argument: num 235444537
// CONFIG
// config: double 1
// config: num 2
// TYPE PATH:
//  double
//  num
// **************************************************************************
// no interceptor for [bool]
// type arguments[1]:
// type arguments[2]:
// can be singleton: FALSE
// parent: Object [@pragma pragma(String name, [Object? options])]
// CONFIG
// config: bool 1
// TYPE PATH:
//  bool
// **************************************************************************
// no interceptor for [void]
// type arguments[1]:
// type arguments[2]:
// **************************************************************************
// interceptor for [generics.SimpleGeneric<generics.Param>]
// type arguments[1]:
// T[516375725] => Param[356184557]
// type arguments[2]:
// ENCLOSING: XXX
// Param[33788864]
// can be singleton: TRUE
// parameter: T 516375725
// argument: T 516375725
// parent: Object [@pragma pragma(String name, [Object? options])]
// parent: Pluggable []
// plugin: PluginOnGeneric
// CONFIG
// config: generics.SimpleGeneric 1
// TYPE PATH:
//  generics.SimpleGeneric
//parametrized type
class $generics_SimpleGeneric_generics_Param_
    extends generics.SimpleGeneric<generics.Param> implements Pluggable {
  late PluginOnGeneric pluginOnGeneric;
  $generics_SimpleGeneric() {
    pluginOnGeneric = new $PluginOnGeneric(this);
  }

  T plugin<T>() {
    if (T == PluginOnGeneric) {
      return pluginOnGeneric as T;
    }
    throw new Exception('no plugin for this type');
  }
}

// **************************************************************************
// no interceptor for [A]
// type arguments[1]:
// type arguments[2]:
// **************************************************************************
// no interceptor for [B]
// type arguments[1]:
// type arguments[2]:
// **************************************************************************
// no interceptor for [generics.ComplexGeneric<generics.Param,A>]
// type arguments[1]:
// A[99844900] => Param[356184557]
// B[364591990] => A[517102781]
// type arguments[2]:
// ENCLOSING: XXX
// Param[33788864]
// ENCLOSING: NULL
// A[846069130]
// can be singleton: FALSE
// parameter: A 99844900
// parameter: B 364591990
// argument: A 99844900
// argument: B 364591990
// parent: Object [@pragma pragma(String name, [Object? options])]
// CONFIG
// config: generics.ComplexGeneric 1
// TYPE PATH:
//  generics.ComplexGeneric
// **************************************************************************
// no interceptor for [TypePlugin<foo.Foo>]
// type arguments[1]:
// T[380287154] => Foo[4632883]
// type arguments[2]:
// ENCLOSING: XXX
// Foo[168697686]
// can be singleton: FALSE
// parameter: T 380287154
// argument: T 380287154
// parent: Object [@pragma pragma(String name, [Object? options])]
// CONFIG
// config: TypePlugin 1
// TYPE PATH:
//  TypePlugin
// **************************************************************************
// no interceptor for [List<dynamic>]
// type arguments[1]:
// T[265238202] => E[263610483]
// E[268730869] => E[263610483]
// E[263610483] => dynamic[1]
// type arguments[2]:
// ENCLOSING: NULL
// dynamic[690028263]
// can be singleton: FALSE
// parameter: E 263610483
// argument: E 263610483
// parent: Object [@pragma pragma(String name, [Object? options])]
// parent: EfficientLengthIterable []
// parameter: T 265238202
// argument: E 263610483
// parent: Iterable []
// parameter: E 268730869
// argument: E 263610483
// CONFIG
// config: List 1
// TYPE PATH:
//  List
// **************************************************************************
// no interceptor for [generics.SimpleGeneric<dynamic>]
// type arguments[1]:
// T[516375725] => dynamic[1]
// type arguments[2]:
// ENCLOSING: NULL
// dynamic[690028263]
// can be singleton: FALSE
// parameter: T 516375725
// argument: T 516375725
// parent: Object [@pragma pragma(String name, [Object? options])]
// parent: Pluggable []
// plugin: PluginOnGeneric
// CONFIG
// config: generics.SimpleGeneric 1
// TYPE PATH:
//  generics.SimpleGeneric
// **************************************************************************
// no interceptor for [TypePlugin<generics.SimpleGeneric<dynamic>>]
// type arguments[1]:
// T[380287154] => SimpleGeneric<dynamic>[179991359]
// type arguments[2]:
// ENCLOSING: XXX
// SimpleGeneric<dynamic>[968382099]
// can be singleton: FALSE
// parameter: T 380287154
// argument: T 380287154
// parent: Object [@pragma pragma(String name, [Object? options])]
// CONFIG
// config: TypePlugin 1
// TYPE PATH:
//  TypePlugin
// **************************************************************************
// no interceptor for [generics.SimpleGeneric<T>]
// type arguments[1]:
// T[516375725] => T[86505154]
// type arguments[2]:
// ENCLOSING: NULL
// T[922847711]
// can be singleton: FALSE
// parameter: T 516375725
// argument: T 516375725
// parent: Object [@pragma pragma(String name, [Object? options])]
// parent: Pluggable []
// plugin: PluginOnGeneric
// CONFIG
// config: generics.SimpleGeneric 1
// TYPE PATH:
//  generics.SimpleGeneric
// **************************************************************************
// interceptor for [AbstractGeneric<foo.Foo>]
// type arguments[1]:
// T[86505154] => Foo[4632883]
// type arguments[2]:
// ENCLOSING: XXX
// Foo[168697686]
// can be singleton: TRUE
// parameter: T 86505154
// argument: T 86505154
// parent: Object [@pragma pragma(String name, [Object? options])]
// CONFIG
// config: AbstractGeneric 1
// TYPE PATH:
//  AbstractGeneric
//parametrized type
class $AbstractGeneric_foo_Foo_ extends AbstractGeneric<foo.Foo>
    implements Pluggable {
  $AbstractGeneric() {}
  T plugin<T>() {
    throw new Exception('no plugin for this type');
  }

// foo.Foo element
// c: foo.Foo
// c: foo.FooChild
// c: foo.FooChild2
  foo.Foo get element => $om.foo_Foo;
// generics.SimpleGeneric<foo.Foo> generic
// c: generics.SimpleGeneric<foo.Foo>
  generics.SimpleGeneric<foo.Foo> get generic =>
      $om.generics_SimpleGeneric_foo_Foo_;
}

// **************************************************************************
// interceptor for [generics.SimpleGeneric<foo.Foo>]
// type arguments[1]:
// T[516375725] => T[86505154]
// type arguments[2]:
// ENCLOSING: XXX
// Foo[168697686]
// can be singleton: TRUE
// parameter: T 516375725
// argument: T 516375725
// parent: Object [@pragma pragma(String name, [Object? options])]
// parent: Pluggable []
// plugin: PluginOnGeneric
// CONFIG
// config: generics.SimpleGeneric 1
// TYPE PATH:
//  generics.SimpleGeneric
//parametrized type
class $generics_SimpleGeneric_foo_Foo_ extends generics.SimpleGeneric<foo.Foo>
    implements Pluggable {
  late PluginOnGeneric pluginOnGeneric;
  $generics_SimpleGeneric() {
    pluginOnGeneric = new $PluginOnGeneric(this);
  }

  T plugin<T>() {
    if (T == PluginOnGeneric) {
      return pluginOnGeneric as T;
    }
    throw new Exception('no plugin for this type');
  }
}

// **************************************************************************
// no interceptor for [AbstractGeneric<T>]
// type arguments[1]:
// T[86505154] => T[462569427]
// type arguments[2]:
// ENCLOSING: NULL
// T[922847711]
// can be singleton: FALSE
// parameter: T 86505154
// argument: T 86505154
// parent: Object [@pragma pragma(String name, [Object? options])]
// CONFIG
// config: AbstractGeneric 1
// TYPE PATH:
//  AbstractGeneric
// **************************************************************************
// no interceptor for [GenericContainer<foo.Foo>]
// type arguments[1]:
// T[462569427] => Foo[4632883]
// type arguments[2]:
// ENCLOSING: XXX
// Foo[168697686]
// can be singleton: FALSE
// parameter: T 462569427
// argument: T 462569427
// parent: Object [@pragma pragma(String name, [Object? options])]
// CONFIG
// config: GenericContainer 1
// TYPE PATH:
//  GenericContainer
// **************************************************************************
// no interceptor for [SubtypesOf<T>]
// type arguments[1]:
// T[473656069] => T[473656069]
// type arguments[2]:
// ENCLOSING: NULL
// T[922847711]
// can be singleton: FALSE
// parameter: T 473656069
// argument: T 473656069
// parent: Object [@pragma pragma(String name, [Object? options])]
// CONFIG
// config: SubtypesOf 1
// TYPE PATH:
//  SubtypesOf
// **************************************************************************
// no interceptor for [TypePlugin<T>]
// type arguments[1]:
// T[380287154] => T[380287154]
// type arguments[2]:
// ENCLOSING: NULL
// T[922847711]
// can be singleton: FALSE
// parameter: T 380287154
// argument: T 380287154
// parent: Object [@pragma pragma(String name, [Object? options])]
// CONFIG
// config: TypePlugin 1
// TYPE PATH:
//  TypePlugin
// **************************************************************************
// no interceptor for [generics.ComplexGeneric<A,B>]
// type arguments[1]:
// A[99844900] => A[99844900]
// B[364591990] => B[364591990]
// type arguments[2]:
// ENCLOSING: NULL
// A[846069130]
// ENCLOSING: NULL
// B[723507287]
// can be singleton: FALSE
// parameter: A 99844900
// parameter: B 364591990
// argument: A 99844900
// argument: B 364591990
// parent: Object [@pragma pragma(String name, [Object? options])]
// CONFIG
// config: generics.ComplexGeneric 1
// TYPE PATH:
//  generics.ComplexGeneric
// **************************************************************************
// no interceptor for [generics.SuperComplexGeneric<A,B>]
// type arguments[1]:
// A[99844900] => Param[356184557]
// B[364591990] => A[517102781]
// A[517102781] => A[517102781]
// B[258296657] => B[258296657]
// type arguments[2]:
// ENCLOSING: NULL
// A[846069130]
// ENCLOSING: NULL
// B[723507287]
// can be singleton: FALSE
// parameter: A 517102781
// parameter: B 258296657
// argument: A 517102781
// argument: B 258296657
// parent: ComplexGeneric [@bool get Compose]
// parameter: A 99844900
// parameter: B 364591990
// argument: Param 356184557
// argument: A 517102781
// parent: Object [@pragma pragma(String name, [Object? options])]
// CONFIG
// config: generics.SuperComplexGeneric 1
// config: generics.ComplexGeneric 2
// TYPE PATH:
//  generics.SuperComplexGeneric
//  generics.ComplexGeneric
// **************************************************************************
// no interceptor for [TypePlugin<generics.SimpleGeneric>]
// type arguments[1]:
// T[380287154] => T[380287154]
// type arguments[2]:
// ENCLOSING: XXX
// SimpleGeneric<T>[380387544]
// can be singleton: FALSE
// parameter: T 380287154
// argument: T 380287154
// parent: Object [@pragma pragma(String name, [Object? options])]
// CONFIG
// config: TypePlugin 1
// TYPE PATH:
//  TypePlugin
// **************************************************************************
// no interceptor for [GenericContainer<T>]
// type arguments[1]:
// T[462569427] => T[462569427]
// type arguments[2]:
// ENCLOSING: NULL
// T[922847711]
// can be singleton: FALSE
// parameter: T 462569427
// argument: T 462569427
// parent: Object [@pragma pragma(String name, [Object? options])]
// CONFIG
// config: GenericContainer 1
// TYPE PATH:
//  GenericContainer
// **************************************************************************
// no interceptor for [num]
// type arguments[1]:
// T[99862877] => num[235444537]
// type arguments[2]:
// can be singleton: FALSE
// parent: Object [@pragma pragma(String name, [Object? options])]
// parent: Comparable []
// parameter: T 99862877
// argument: num 235444537
// CONFIG
// config: num 1
// TYPE PATH:
//  num
// **************************************************************************
class $ObjectManager {
  $foo_Foo? _foo_Foo;
  $foo_Foo get foo_Foo {
    if (_foo_Foo == null) {
      _foo_Foo = new $foo_Foo();
    }
    return _foo_Foo as $foo_Foo;
  }

  $foo_FooChild? _foo_FooChild;
  $foo_FooChild get foo_FooChild {
    if (_foo_FooChild == null) {
      _foo_FooChild = new $foo_FooChild();
    }
    return _foo_FooChild as $foo_FooChild;
  }

  $bar_Bar? _bar_Bar;
  $bar_Bar get bar_Bar {
    if (_bar_Bar == null) {
      _bar_Bar = new $bar_Bar();
    }
    return _bar_Bar as $bar_Bar;
  }

  $bar_BarChild? _bar_BarChild;
  $bar_BarChild get bar_BarChild {
    if (_bar_BarChild == null) {
      _bar_BarChild = new $bar_BarChild();
    }
    return _bar_BarChild as $bar_BarChild;
  }

  $generics_Param? _generics_Param;
  $generics_Param get generics_Param {
    if (_generics_Param == null) {
      _generics_Param = new $generics_Param();
    }
    return _generics_Param as $generics_Param;
  }

  $generics_SimpleSpecific? _generics_SimpleSpecific;
  $generics_SimpleSpecific get generics_SimpleSpecific {
    if (_generics_SimpleSpecific == null) {
      _generics_SimpleSpecific = new $generics_SimpleSpecific();
    }
    return _generics_SimpleSpecific as $generics_SimpleSpecific;
  }

  $GenericTypedWithFoo? _genericTypedWithFoo;
  $GenericTypedWithFoo get genericTypedWithFoo {
    if (_genericTypedWithFoo == null) {
      _genericTypedWithFoo = new $GenericTypedWithFoo();
    }
    return _genericTypedWithFoo as $GenericTypedWithFoo;
  }

  $ContainerFoo? _containerFoo;
  $ContainerFoo get containerFoo {
    if (_containerFoo == null) {
      _containerFoo = new $ContainerFoo();
    }
    return _containerFoo as $ContainerFoo;
  }

  $generics_SimpleGeneric_generics_Param_?
      _generics_SimpleGeneric_generics_Param_;
  $generics_SimpleGeneric_generics_Param_
      get generics_SimpleGeneric_generics_Param_ {
    if (_generics_SimpleGeneric_generics_Param_ == null) {
      _generics_SimpleGeneric_generics_Param_ =
          new $generics_SimpleGeneric_generics_Param_();
    }
    return _generics_SimpleGeneric_generics_Param_
        as $generics_SimpleGeneric_generics_Param_;
  }

  $AbstractGeneric_foo_Foo_? _abstractGeneric_foo_Foo_;
  $AbstractGeneric_foo_Foo_ get abstractGeneric_foo_Foo_ {
    if (_abstractGeneric_foo_Foo_ == null) {
      _abstractGeneric_foo_Foo_ = new $AbstractGeneric_foo_Foo_();
    }
    return _abstractGeneric_foo_Foo_ as $AbstractGeneric_foo_Foo_;
  }

  $generics_SimpleGeneric_foo_Foo_? _generics_SimpleGeneric_foo_Foo_;
  $generics_SimpleGeneric_foo_Foo_ get generics_SimpleGeneric_foo_Foo_ {
    if (_generics_SimpleGeneric_foo_Foo_ == null) {
      _generics_SimpleGeneric_foo_Foo_ = new $generics_SimpleGeneric_foo_Foo_();
    }
    return _generics_SimpleGeneric_foo_Foo_ as $generics_SimpleGeneric_foo_Foo_;
  }
}

$ObjectManager $om = new $ObjectManager();
//generated in 8ms
