// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'subtypes.dart';

// **************************************************************************
// SwiftGenerator
// **************************************************************************

// **************************************************************************
// generated by swift_composer at 2022-02-13 19:49:20.555302
// config file for module_test1: /home/fsw/workspace/swift_composer/test/lib/foo.di.yaml
// **************************************************************************
// ALL TYPES INFO
// **************************************************************************
// SubtypesOf => SubtypesOf  GENERIC [T = T   47246589 = 47246589   47246589 = TypeParameterTypeImpl]
// AnnotatedWith => AnnotatedWith   [      ]
// Pluggable => Pluggable   [      ]
// TypePlugin => TypePlugin  GENERIC [T = T   69357257 = 69357257   69357257 = TypeParameterTypeImpl]
// module_test1.Foo => module_test1.Foo INTERCEPTED  [      ]
// module_test1.FooChild => module_test1.FooChild INTERCEPTED  [      ]
// module_test1.FooChild2 => module_test1.FooChild2 INTERCEPTED  [      ]
// Container => Container INTERCEPTED  [      ]
// Object => Object   [      ]
// String => String   [T = String   459756122 = 153217077   459756122 = InterfaceTypeImpl]
// List<String> => List<String>   [T = E,E = String   194905962 = 40007411,40007411 = 153217077   194905962 = TypeParameterTypeImpl,40007411 = InterfaceTypeImpl]
// T => T   [      ]
// List<T> => List<T>   [T = E,E = T   194905962 = 40007411,40007411 = 47246589   194905962 = TypeParameterTypeImpl,40007411 = TypeParameterTypeImpl]
// dynamic => dynamic   [      ]
// ST => ST   [      ]
// int => int   [T = num   459756122 = 148975391   459756122 = InterfaceTypeImpl]
// double => double   [T = num   459756122 = 148975391   459756122 = InterfaceTypeImpl]
// bool => bool   [      ]
// Map<String,module_test1.Foo> => Map<String,module_test1.Foo>   [K = String,V = Foo   339746579 = 153217077,119869657 = 160765256   339746579 = InterfaceTypeImpl,119869657 = InterfaceTypeImpl]
// **************************************************************************
// no interceptor for [SubtypesOf]
// type arguments[1]:
// T[47246589] => T[47246589]
// type arguments[2]:
// can be singleton: FALSE
// parameter: T 47246589
// argument: T 47246589
// parent: Object [@pragma pragma(String name, [Object? options])]
// CONFIG
// config: module_test1.Foo {stringField: FooField, integerField: 124}
// config: module_test1.FooChild {stringField: FooChildField, doubleField: 0.55, booleanField: true}
// config: module_test1.FooChild2 {stringField: FooChild2Field, doubleField: 0.55, booleanField: true}
// config: SubtypesOf 1
// TYPE PATH:
//  SubtypesOf
// **************************************************************************
// no interceptor for [AnnotatedWith]
// type arguments[1]:
// type arguments[2]:
// can be singleton: FALSE
// parent: Object [@pragma pragma(String name, [Object? options])]
// CONFIG
// config: module_test1.Foo {stringField: FooField, integerField: 124}
// config: module_test1.FooChild {stringField: FooChildField, doubleField: 0.55, booleanField: true}
// config: module_test1.FooChild2 {stringField: FooChild2Field, doubleField: 0.55, booleanField: true}
// config: AnnotatedWith 1
// TYPE PATH:
//  AnnotatedWith
// **************************************************************************
// no interceptor for [Pluggable]
// type arguments[1]:
// type arguments[2]:
// can be singleton: FALSE
// parent: Object [@pragma pragma(String name, [Object? options])]
// CONFIG
// config: module_test1.Foo {stringField: FooField, integerField: 124}
// config: module_test1.FooChild {stringField: FooChildField, doubleField: 0.55, booleanField: true}
// config: module_test1.FooChild2 {stringField: FooChild2Field, doubleField: 0.55, booleanField: true}
// config: Pluggable 1
// TYPE PATH:
//  Pluggable
// **************************************************************************
// no interceptor for [TypePlugin]
// type arguments[1]:
// T[69357257] => T[69357257]
// type arguments[2]:
// can be singleton: FALSE
// parameter: T 69357257
// argument: T 69357257
// parent: Object [@pragma pragma(String name, [Object? options])]
// CONFIG
// config: module_test1.Foo {stringField: FooField, integerField: 124}
// config: module_test1.FooChild {stringField: FooChildField, doubleField: 0.55, booleanField: true}
// config: module_test1.FooChild2 {stringField: FooChild2Field, doubleField: 0.55, booleanField: true}
// config: TypePlugin 1
// TYPE PATH:
//  TypePlugin
// **************************************************************************
// interceptor for [module_test1.Foo]
// type arguments[1]:
// type arguments[2]:
// can be singleton: TRUE
// parent: Object [@pragma pragma(String name, [Object? options])]
// parent: Pluggable []
// CONFIG
// config: module_test1.Foo {stringField: FooField, integerField: 124}
// config: module_test1.FooChild {stringField: FooChildField, doubleField: 0.55, booleanField: true}
// config: module_test1.FooChild2 {stringField: FooChild2Field, doubleField: 0.55, booleanField: true}
// config: module_test1.Foo 1
// config: stringField FooField
// config: integerField 124
// TYPE PATH:
//  module_test1.Foo
class $module_test1_Foo extends module_test1.Foo implements Pluggable {
  $module_test1_Foo() {}
  T plugin<T>() {
    throw new Exception('no plugin for this type');
  }

// String className
// c: String
  String get className => "module_test1.Foo";
// String stringField
// c: String
  String get stringField => "FooField";
// int integerField
// c: int
  int get integerField => 124;
}

// **************************************************************************
// interceptor for [module_test1.FooChild]
// type arguments[1]:
// type arguments[2]:
// can be singleton: TRUE
// parent: Foo [@bool get Compose]
// parent: Object [@pragma pragma(String name, [Object? options])]
// parent: Pluggable []
// CONFIG
// config: module_test1.Foo {stringField: FooField, integerField: 124}
// config: module_test1.FooChild {stringField: FooChildField, doubleField: 0.55, booleanField: true}
// config: module_test1.FooChild2 {stringField: FooChild2Field, doubleField: 0.55, booleanField: true}
// config: module_test1.FooChild 1
// config: stringField FooChildField
// config: doubleField 0.55
// config: booleanField true
// config: module_test1.Foo 2
// config: integerField 124
// TYPE PATH:
//  module_test1.FooChild
//  module_test1.Foo
class $module_test1_FooChild extends module_test1.FooChild
    implements Pluggable {
  $module_test1_FooChild() {}
  T plugin<T>() {
    throw new Exception('no plugin for this type');
  }

// double doubleField
// c: double
  double get doubleField => 0.55;
// bool booleanField
// c: bool
  bool get booleanField => true;
// String className
// c: String
  String get className => "module_test1.FooChild";
// String stringField
// c: String
  String get stringField => "FooChildField";
// int integerField
// c: int
  int get integerField => 124;
}

// **************************************************************************
// interceptor for [module_test1.FooChild2]
// type arguments[1]:
// type arguments[2]:
// can be singleton: FALSE
// parent: Foo [@bool get Compose]
// parent: Object [@pragma pragma(String name, [Object? options])]
// parent: Pluggable []
// CONFIG
// config: module_test1.Foo {stringField: FooField, integerField: 124}
// config: module_test1.FooChild {stringField: FooChildField, doubleField: 0.55, booleanField: true}
// config: module_test1.FooChild2 {stringField: FooChild2Field, doubleField: 0.55, booleanField: true}
// config: module_test1.FooChild2 1
// config: stringField FooChild2Field
// config: doubleField 0.55
// config: booleanField true
// config: module_test1.Foo 2
// config: integerField 124
// TYPE PATH:
//  module_test1.FooChild2
//  module_test1.Foo
class $module_test1_FooChild2 extends module_test1.FooChild2
    implements Pluggable {
  $module_test1_FooChild2(requiredString) {
//String
    this.requiredString = requiredString;
  }
  T plugin<T>() {
    throw new Exception('no plugin for this type');
  }

// String requiredString
// c: String
// String className
// c: String
  String get className => "module_test1.FooChild2";
// String stringField
// c: String
  String get stringField => "FooChild2Field";
// int integerField
// c: int
  int get integerField => 124;
}

// **************************************************************************
// interceptor for [Container]
// type arguments[1]:
// type arguments[2]:
// can be singleton: TRUE
// parent: Object [@pragma pragma(String name, [Object? options])]
// CONFIG
// config: module_test1.Foo {stringField: FooField, integerField: 124}
// config: module_test1.FooChild {stringField: FooChildField, doubleField: 0.55, booleanField: true}
// config: module_test1.FooChild2 {stringField: FooChild2Field, doubleField: 0.55, booleanField: true}
// config: Container 1
// TYPE PATH:
//  Container
class $Container extends Container implements Pluggable {
  $Container() {}
  T plugin<T>() {
    throw new Exception('no plugin for this type');
  }

// Map<String,module_test1.Foo> instances
// c: Map<String,module_test1.Foo>
  Map<String, module_test1.Foo> get instances =>
      $om.instancesOfmodule_test1_Foo;
  module_test1.Foo factory(String className) {
    switch (className) {
      case 'module_test1.Foo':
        return new $module_test1_Foo();
      case 'module_test1.FooChild':
        return new $module_test1_FooChild();
    }
    throw new Exception('no type for ' + className);
  }
}

// **************************************************************************
// no interceptor for [Object]
// type arguments[1]:
// type arguments[2]:
// can be singleton: FALSE
// CONFIG
// config: module_test1.Foo {stringField: FooField, integerField: 124}
// config: module_test1.FooChild {stringField: FooChildField, doubleField: 0.55, booleanField: true}
// config: module_test1.FooChild2 {stringField: FooChild2Field, doubleField: 0.55, booleanField: true}
// config: Object 1
// TYPE PATH:
//  Object
// **************************************************************************
// no interceptor for [String]
// type arguments[1]:
// T[459756122] => String[153217077]
// type arguments[2]:
// can be singleton: FALSE
// parent: Object [@pragma pragma(String name, [Object? options])]
// parent: Comparable []
// parameter: T 459756122
// argument: String 153217077
// parent: Pattern []
// CONFIG
// config: module_test1.Foo {stringField: FooField, integerField: 124}
// config: module_test1.FooChild {stringField: FooChildField, doubleField: 0.55, booleanField: true}
// config: module_test1.FooChild2 {stringField: FooChild2Field, doubleField: 0.55, booleanField: true}
// config: String 1
// TYPE PATH:
//  String
// **************************************************************************
// no interceptor for [List<String>]
// type arguments[1]:
// T[194905962] => E[40007411]
// E[37912016] => E[40007411]
// E[40007411] => String[153217077]
// type arguments[2]:
// ENCLOSING: XXX
// String[245041371]
// can be singleton: FALSE
// parameter: E 40007411
// argument: E 40007411
// parent: Object [@pragma pragma(String name, [Object? options])]
// parent: EfficientLengthIterable []
// parameter: T 194905962
// argument: E 40007411
// parent: Iterable []
// parameter: E 37912016
// argument: E 40007411
// CONFIG
// config: module_test1.Foo {stringField: FooField, integerField: 124}
// config: module_test1.FooChild {stringField: FooChildField, doubleField: 0.55, booleanField: true}
// config: module_test1.FooChild2 {stringField: FooChild2Field, doubleField: 0.55, booleanField: true}
// config: List 1
// TYPE PATH:
//  List
// **************************************************************************
// no interceptor for [T]
// type arguments[1]:
// type arguments[2]:
// **************************************************************************
// no interceptor for [List<T>]
// type arguments[1]:
// T[194905962] => E[40007411]
// E[37912016] => E[40007411]
// E[40007411] => T[47246589]
// type arguments[2]:
// ENCLOSING: NULL
// T[840748941]
// can be singleton: FALSE
// parameter: E 40007411
// argument: E 40007411
// parent: Object [@pragma pragma(String name, [Object? options])]
// parent: EfficientLengthIterable []
// parameter: T 194905962
// argument: E 40007411
// parent: Iterable []
// parameter: E 37912016
// argument: E 40007411
// CONFIG
// config: module_test1.Foo {stringField: FooField, integerField: 124}
// config: module_test1.FooChild {stringField: FooChildField, doubleField: 0.55, booleanField: true}
// config: module_test1.FooChild2 {stringField: FooChild2Field, doubleField: 0.55, booleanField: true}
// config: List 1
// TYPE PATH:
//  List
// **************************************************************************
// no interceptor for [dynamic]
// type arguments[1]:
// type arguments[2]:
// **************************************************************************
// no interceptor for [ST]
// type arguments[1]:
// type arguments[2]:
// **************************************************************************
// no interceptor for [int]
// type arguments[1]:
// T[459756122] => num[148975391]
// type arguments[2]:
// can be singleton: FALSE
// parent: num []
// parent: Object [@pragma pragma(String name, [Object? options])]
// parent: Comparable []
// parameter: T 459756122
// argument: num 148975391
// CONFIG
// config: module_test1.Foo {stringField: FooField, integerField: 124}
// config: module_test1.FooChild {stringField: FooChildField, doubleField: 0.55, booleanField: true}
// config: module_test1.FooChild2 {stringField: FooChild2Field, doubleField: 0.55, booleanField: true}
// config: int 1
// config: num 2
// TYPE PATH:
//  int
//  num
// **************************************************************************
// no interceptor for [double]
// type arguments[1]:
// T[459756122] => num[148975391]
// type arguments[2]:
// can be singleton: FALSE
// parent: num []
// parent: Object [@pragma pragma(String name, [Object? options])]
// parent: Comparable []
// parameter: T 459756122
// argument: num 148975391
// CONFIG
// config: module_test1.Foo {stringField: FooField, integerField: 124}
// config: module_test1.FooChild {stringField: FooChildField, doubleField: 0.55, booleanField: true}
// config: module_test1.FooChild2 {stringField: FooChild2Field, doubleField: 0.55, booleanField: true}
// config: double 1
// config: num 2
// TYPE PATH:
//  double
//  num
// **************************************************************************
// no interceptor for [bool]
// type arguments[1]:
// type arguments[2]:
// can be singleton: FALSE
// parent: Object [@pragma pragma(String name, [Object? options])]
// CONFIG
// config: module_test1.Foo {stringField: FooField, integerField: 124}
// config: module_test1.FooChild {stringField: FooChildField, doubleField: 0.55, booleanField: true}
// config: module_test1.FooChild2 {stringField: FooChild2Field, doubleField: 0.55, booleanField: true}
// config: bool 1
// TYPE PATH:
//  bool
// **************************************************************************
// no interceptor for [Map<String,module_test1.Foo>]
// type arguments[1]:
// K[339746579] => String[153217077]
// V[119869657] => Foo[160765256]
// type arguments[2]:
// ENCLOSING: XXX
// String[245041371]
// ENCLOSING: XXX
// Foo[79082427]
// can be singleton: FALSE
// parameter: K 339746579
// parameter: V 119869657
// argument: K 339746579
// argument: V 119869657
// parent: Object [@pragma pragma(String name, [Object? options])]
// CONFIG
// config: module_test1.Foo {stringField: FooField, integerField: 124}
// config: module_test1.FooChild {stringField: FooChildField, doubleField: 0.55, booleanField: true}
// config: module_test1.FooChild2 {stringField: FooChild2Field, doubleField: 0.55, booleanField: true}
// config: Map 1
// TYPE PATH:
//  Map
// **************************************************************************
// no interceptor for [SubtypesOf<T>]
// type arguments[1]:
// T[47246589] => T[47246589]
// type arguments[2]:
// ENCLOSING: NULL
// T[840748941]
// can be singleton: FALSE
// parameter: T 47246589
// argument: T 47246589
// parent: Object [@pragma pragma(String name, [Object? options])]
// CONFIG
// config: module_test1.Foo {stringField: FooField, integerField: 124}
// config: module_test1.FooChild {stringField: FooChildField, doubleField: 0.55, booleanField: true}
// config: module_test1.FooChild2 {stringField: FooChild2Field, doubleField: 0.55, booleanField: true}
// config: SubtypesOf 1
// TYPE PATH:
//  SubtypesOf
// **************************************************************************
// no interceptor for [TypePlugin<T>]
// type arguments[1]:
// T[69357257] => T[69357257]
// type arguments[2]:
// ENCLOSING: NULL
// T[840748941]
// can be singleton: FALSE
// parameter: T 69357257
// argument: T 69357257
// parent: Object [@pragma pragma(String name, [Object? options])]
// CONFIG
// config: module_test1.Foo {stringField: FooField, integerField: 124}
// config: module_test1.FooChild {stringField: FooChildField, doubleField: 0.55, booleanField: true}
// config: module_test1.FooChild2 {stringField: FooChild2Field, doubleField: 0.55, booleanField: true}
// config: TypePlugin 1
// TYPE PATH:
//  TypePlugin
// **************************************************************************
// no interceptor for [num]
// type arguments[1]:
// T[459756122] => num[148975391]
// type arguments[2]:
// can be singleton: FALSE
// parent: Object [@pragma pragma(String name, [Object? options])]
// parent: Comparable []
// parameter: T 459756122
// argument: num 148975391
// CONFIG
// config: module_test1.Foo {stringField: FooField, integerField: 124}
// config: module_test1.FooChild {stringField: FooChildField, doubleField: 0.55, booleanField: true}
// config: module_test1.FooChild2 {stringField: FooChild2Field, doubleField: 0.55, booleanField: true}
// config: num 1
// TYPE PATH:
//  num
// **************************************************************************
class $ObjectManager {
  $module_test1_Foo? _module_test1_Foo;
  $module_test1_Foo get module_test1_Foo {
    if (_module_test1_Foo == null) {
      _module_test1_Foo = new $module_test1_Foo();
    }
    return _module_test1_Foo as $module_test1_Foo;
  }

  $module_test1_FooChild? _module_test1_FooChild;
  $module_test1_FooChild get module_test1_FooChild {
    if (_module_test1_FooChild == null) {
      _module_test1_FooChild = new $module_test1_FooChild();
    }
    return _module_test1_FooChild as $module_test1_FooChild;
  }

  $Container? _container;
  $Container get container {
    if (_container == null) {
      _container = new $Container();
    }
    return _container as $Container;
  }

  Map<String, module_test1.Foo> get instancesOfmodule_test1_Foo {
    return {
      "module_test1.Foo": new $module_test1_Foo(),
      "module_test1.FooChild": new $module_test1_FooChild(),
    };
  }
}

$ObjectManager $om = new $ObjectManager();
//generated in 14ms
