// GENERATED CODE - DO NOT MODIFY BY HAND
// dart format width=80

part of 'namespaces.dart';

// **************************************************************************
// SwiftGenerator
// **************************************************************************

// **************************************************************************
// generated by swift_composer at 2025-11-17 12:05:14.003755
// ignore common warnings in generated code, you can also exclude this file in analysis_options.yaml
// ignore_for_file: unnecessary_non_null_assertion
// ignore_for_file: dead_null_aware_expression
// **************************************************************************
// CONFIG
// config file for nested_module: test/lib/nested.di.yaml
// config file for foo2_module: test/lib/foo2.di.yaml
// config file for bar_module: test/lib/bar.di.yaml
// no config file for generics_module: test/lib/generics.di.yaml
// no config file for root: lib/swift_composer.di.yaml
// no config file for root: test/namespaces/namespaces.di.yaml
// **************************************************************************
// MERGED CONFIG
// nested_module.Foo: {stringField: NestedFooField, integerField: 124}
// nested_module.FooChild: {stringField: NestedFooChildField, doubleField: 0.55, booleanField: true}
// nested_module.FooChild2: {stringField: NestedFooChild2Field, doubleField: 0.55, booleanField: true}
// foo2_module.Foo: {stringField2: Foo2Field}
// bar_module.Bar: {stringField: BarStringField}
// bar_module.BarChild: {stringField: BarChildStringField}
// **************************************************************************
//register: ComposeIfModule
//register: SubtypeInfo
//register: SubtypesOf
//register: UnknownTypeException
//register: AnnotatedWith
//register: Pluggable
//register: TypePlugin
//register: nested_module.CombinedFoo
//register: nested_module.Foo
//register: nested_module.FooChild
//register: nested_module.FooChild2
//register: foo2_module.Foo
//register: bar_module.Bar
//register: bar_module.BarChild
//register: generics_module.SimpleGeneric
//register: generics_module.Param
//register: generics_module.SimpleSpecific
//register: generics_module.ComplexGeneric
//register: generics_module.SuperComplexGeneric
//register: Foo
//register: RootClass
//register: GenericRootClass
//register: SpecificRootClass
// **************************************************************************
class $nested_module_CombinedFoo extends nested_module.CombinedFoo
    implements Pluggable {
  $nested_module_CombinedFoo() {}
  T plugin<T>() {
    throw new Exception('no plugin for this type');
  }

  String get className => $om.s[0];
  nested_module.Foo get inner_module_Foo1 => $om.nested_module_Foo;
}

// **************************************************************************
class $nested_module_Foo extends nested_module.Foo implements Pluggable {
  $nested_module_Foo() {}
  T plugin<T>() {
    throw new Exception('no plugin for this type');
  }

  String get className => $om.s[1];
  String get stringField => "NestedFooField";
  int get integerField => 124;
}

// **************************************************************************
class $nested_module_FooChild extends nested_module.FooChild
    implements Pluggable {
  $nested_module_FooChild() {}
  T plugin<T>() {
    throw new Exception('no plugin for this type');
  }

  double get doubleField => 0.55;
  bool get booleanField => true;
  String get className => $om.s[2];
  String get stringField => "NestedFooChildField";
  int get integerField => 124;
}

// **************************************************************************
class $nested_module_FooChild2 extends nested_module.FooChild2
    implements Pluggable {
  $nested_module_FooChild2(requiredString) {
    this.requiredString = requiredString;
  }
  T plugin<T>() {
    throw new Exception('no plugin for this type');
  }

  String get className => $om.s[3];
  String get stringField => "NestedFooChild2Field";
  int get integerField => 124;
}

// **************************************************************************
class $foo2_module_Foo extends foo2_module.Foo implements Pluggable {
  $foo2_module_Foo() {}
  T plugin<T>() {
    throw new Exception('no plugin for this type');
  }

  String get className => $om.s[4];
  String? get stringField2 => "Foo2Field";
}

// **************************************************************************
class $bar_module_Bar extends bar_module.Bar implements Pluggable {
  $bar_module_Bar() {}
  T plugin<T>() {
    throw new Exception('no plugin for this type');
  }

  List<String> get classNames => [];
  String get stringField => "BarStringField";
}

// **************************************************************************
class $bar_module_BarChild extends bar_module.BarChild implements Pluggable {
  $bar_module_BarChild() {}
  T plugin<T>() {
    throw new Exception('no plugin for this type');
  }

  List<String> get classNames => [$om.s[5]];
  String get stringField => "BarChildStringField";
}

// **************************************************************************
class $generics_module_Param extends generics_module.Param
    implements Pluggable {
  $generics_module_Param() {}
  T plugin<T>() {
    throw new Exception('no plugin for this type');
  }
}

// **************************************************************************
class $generics_module_SimpleSpecific extends generics_module.SimpleSpecific
    implements Pluggable {
  $generics_module_SimpleSpecific() {}
  T plugin<T>() {
    throw new Exception('no plugin for this type');
  }
}

// **************************************************************************
//parametrized type
class $generics_module_SimpleGeneric_generics_module_Param_
    extends generics_module.SimpleGeneric<generics_module.Param>
    implements Pluggable {
  $generics_module_SimpleGeneric_generics_module_Param_() {}
  T plugin<T>() {
    throw new Exception('no plugin for this type');
  }
}

// **************************************************************************
//parametrized type
class $generics_module_SimpleGeneric_Foo_
    extends generics_module.SimpleGeneric<Foo>
    implements Pluggable {
  $generics_module_SimpleGeneric_Foo_() {}
  T plugin<T>() {
    throw new Exception('no plugin for this type');
  }
}

// **************************************************************************
// **************************************************************************
// **************************************************************************
class $ObjectManager {
  $nested_module_CombinedFoo? _nested_module_CombinedFoo;
  $nested_module_CombinedFoo get nested_module_CombinedFoo {
    if (_nested_module_CombinedFoo == null) {
      _nested_module_CombinedFoo = new $nested_module_CombinedFoo();
    }
    return _nested_module_CombinedFoo as $nested_module_CombinedFoo;
  }

  $nested_module_Foo? _nested_module_Foo;
  $nested_module_Foo get nested_module_Foo {
    if (_nested_module_Foo == null) {
      _nested_module_Foo = new $nested_module_Foo();
    }
    return _nested_module_Foo as $nested_module_Foo;
  }

  $nested_module_FooChild? _nested_module_FooChild;
  $nested_module_FooChild get nested_module_FooChild {
    if (_nested_module_FooChild == null) {
      _nested_module_FooChild = new $nested_module_FooChild();
    }
    return _nested_module_FooChild as $nested_module_FooChild;
  }

  $foo2_module_Foo? _foo2_module_Foo;
  $foo2_module_Foo get foo2_module_Foo {
    if (_foo2_module_Foo == null) {
      _foo2_module_Foo = new $foo2_module_Foo();
    }
    return _foo2_module_Foo as $foo2_module_Foo;
  }

  $bar_module_Bar? _bar_module_Bar;
  $bar_module_Bar get bar_module_Bar {
    if (_bar_module_Bar == null) {
      _bar_module_Bar = new $bar_module_Bar();
    }
    return _bar_module_Bar as $bar_module_Bar;
  }

  $bar_module_BarChild? _bar_module_BarChild;
  $bar_module_BarChild get bar_module_BarChild {
    if (_bar_module_BarChild == null) {
      _bar_module_BarChild = new $bar_module_BarChild();
    }
    return _bar_module_BarChild as $bar_module_BarChild;
  }

  $generics_module_Param? _generics_module_Param;
  $generics_module_Param get generics_module_Param {
    if (_generics_module_Param == null) {
      _generics_module_Param = new $generics_module_Param();
    }
    return _generics_module_Param as $generics_module_Param;
  }

  $generics_module_SimpleSpecific? _generics_module_SimpleSpecific;
  $generics_module_SimpleSpecific get generics_module_SimpleSpecific {
    if (_generics_module_SimpleSpecific == null) {
      _generics_module_SimpleSpecific = new $generics_module_SimpleSpecific();
    }
    return _generics_module_SimpleSpecific as $generics_module_SimpleSpecific;
  }

  $generics_module_SimpleGeneric_generics_module_Param_?
  _generics_module_SimpleGeneric_generics_module_Param_;
  $generics_module_SimpleGeneric_generics_module_Param_
  get generics_module_SimpleGeneric_generics_module_Param_ {
    if (_generics_module_SimpleGeneric_generics_module_Param_ == null) {
      _generics_module_SimpleGeneric_generics_module_Param_ =
          new $generics_module_SimpleGeneric_generics_module_Param_();
    }
    return _generics_module_SimpleGeneric_generics_module_Param_
        as $generics_module_SimpleGeneric_generics_module_Param_;
  }

  $generics_module_SimpleGeneric_Foo_? _generics_module_SimpleGeneric_Foo_;
  $generics_module_SimpleGeneric_Foo_ get generics_module_SimpleGeneric_Foo_ {
    if (_generics_module_SimpleGeneric_Foo_ == null) {
      _generics_module_SimpleGeneric_Foo_ =
          new $generics_module_SimpleGeneric_Foo_();
    }
    return _generics_module_SimpleGeneric_Foo_
        as $generics_module_SimpleGeneric_Foo_;
  }

  final List<String> s = const [
    "nested_module.CombinedFoo",
    "nested_module.Foo",
    "nested_module.FooChild",
    "nested_module.FooChild2",
    "foo2_module.Foo",
    "bar_module.BarChild",
  ];
}

$ObjectManager $om = new $ObjectManager();
// generated in 3ms
