// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'namespaces.dart';

// **************************************************************************
// SwiftGenerator
// **************************************************************************

// **************************************************************************
// generated by swift_composer at 2023-02-20 08:04:32.431642
// **************************************************************************
// CONFIG
// no config file for root: /home/fsw/workspace/swift_shop/packages/swift_composer/.dart_tool/..//lib/swift_composer.di.yaml
// config file for nested_module: /home/fsw/workspace/swift_shop/packages/swift_composer/test/namespaces/../lib/nested.di.yaml
// config file for foo2_module: /home/fsw/workspace/swift_shop/packages/swift_composer/test/namespaces/../lib/foo2.di.yaml
// config file for bar_module: /home/fsw/workspace/swift_shop/packages/swift_composer/test/namespaces/../lib/bar.di.yaml
// no config file for generics_module: /home/fsw/workspace/swift_shop/packages/swift_composer/test/namespaces/../lib/generics.di.yaml
// no config file for root: /home/fsw/workspace/swift_shop/packages/swift_composer/test/namespaces/namespaces.di.yaml
// **************************************************************************
// MERGED CONFIG
// nested_module.Foo: {stringField: NestedFooField, integerField: 124}
// nested_module.FooChild: {stringField: NestedFooChildField, doubleField: 0.55, booleanField: true}
// nested_module.FooChild2: {stringField: NestedFooChild2Field, doubleField: 0.55, booleanField: true}
// foo2_module.Foo: {stringField2: Foo2Field}
// bar_module.Bar: {stringField: BarStringField}
// bar_module.BarChild: {stringField: BarChildStringField}
// **************************************************************************
// **************************************************************************
// no interceptor for [SubtypesOf]
// **************************************************************************
// no interceptor for [AnnotatedWith]
// **************************************************************************
// no interceptor for [Pluggable]
// **************************************************************************
// no interceptor for [TypePlugin]
// **************************************************************************
// interceptor for [nested_module.CombinedFoo]
class $nested_module_CombinedFoo extends nested_module.CombinedFoo
    implements Pluggable {
  $nested_module_CombinedFoo() {}
  T plugin<T>() {
    throw new Exception('no plugin for this type');
  }

// String className
  String get className => "nested_module.CombinedFoo";
// nested_module.Foo inner_module_Foo1
  nested_module.Foo get inner_module_Foo1 => $om.nested_module_Foo;
}

// **************************************************************************
// interceptor for [nested_module.Foo]
class $nested_module_Foo extends nested_module.Foo implements Pluggable {
  $nested_module_Foo() {}
  T plugin<T>() {
    throw new Exception('no plugin for this type');
  }

// String className
  String get className => "nested_module.Foo";
// String stringField
  String get stringField => "NestedFooField";
// int integerField
  int get integerField => 124;
}

// **************************************************************************
// interceptor for [nested_module.FooChild]
class $nested_module_FooChild extends nested_module.FooChild
    implements Pluggable {
  $nested_module_FooChild() {}
  T plugin<T>() {
    throw new Exception('no plugin for this type');
  }

// double doubleField
  double get doubleField => 0.55;
// bool booleanField
  bool get booleanField => true;
// String className
  String get className => "nested_module.FooChild";
// String stringField
  String get stringField => "NestedFooChildField";
// int integerField
  int get integerField => 124;
}

// **************************************************************************
// interceptor for [nested_module.FooChild2]
class $nested_module_FooChild2 extends nested_module.FooChild2
    implements Pluggable {
  $nested_module_FooChild2(requiredString) {
//String
    this.requiredString = requiredString;
  }
  T plugin<T>() {
    throw new Exception('no plugin for this type');
  }

// String requiredString
// String className
  String get className => "nested_module.FooChild2";
// String stringField
  String get stringField => "NestedFooChild2Field";
// int integerField
  int get integerField => 124;
}

// **************************************************************************
// interceptor for [foo2_module.Foo]
class $foo2_module_Foo extends foo2_module.Foo implements Pluggable {
  $foo2_module_Foo() {}
  T plugin<T>() {
    throw new Exception('no plugin for this type');
  }

// String className
  String get className => "foo2_module.Foo";
// String? stringField2
  String? get stringField2 => "Foo2Field";
}

// **************************************************************************
// interceptor for [bar_module.Bar]
class $bar_module_Bar extends bar_module.Bar implements Pluggable {
  $bar_module_Bar() {}
  T plugin<T>() {
    throw new Exception('no plugin for this type');
  }

// List<String> classNames
  List<String> get classNames => [];
// String stringField
  String get stringField => "BarStringField";
}

// **************************************************************************
// interceptor for [bar_module.BarChild]
class $bar_module_BarChild extends bar_module.BarChild implements Pluggable {
  $bar_module_BarChild() {}
  T plugin<T>() {
    throw new Exception('no plugin for this type');
  }

// List<String> classNames
  List<String> get classNames => ['bar_module.BarChild'];
// String stringField
  String get stringField => "BarChildStringField";
}

// **************************************************************************
// no interceptor for [generics_module.SimpleGeneric]
// **************************************************************************
// interceptor for [generics_module.Param]
class $generics_module_Param extends generics_module.Param
    implements Pluggable {
  $generics_module_Param() {}
  T plugin<T>() {
    throw new Exception('no plugin for this type');
  }
}

// **************************************************************************
// interceptor for [generics_module.SimpleSpecific]
class $generics_module_SimpleSpecific extends generics_module.SimpleSpecific
    implements Pluggable {
  $generics_module_SimpleSpecific() {}
  T plugin<T>() {
    throw new Exception('no plugin for this type');
  }
}

// **************************************************************************
// no interceptor for [generics_module.ComplexGeneric]
// **************************************************************************
// no interceptor for [generics_module.SuperComplexGeneric]
// **************************************************************************
// no interceptor for [Foo]
// **************************************************************************
// no interceptor for [RootClass]
// **************************************************************************
// no interceptor for [GenericRootClass]
// **************************************************************************
// no interceptor for [SpecificRootClass]
// **************************************************************************
// no interceptor for [Object]
// **************************************************************************
// no interceptor for [String]
// **************************************************************************
// no interceptor for [List<String>]
// **************************************************************************
// no interceptor for [Map<String,String>]
// **************************************************************************
// no interceptor for [T]
// **************************************************************************
// no interceptor for [dynamic]
// **************************************************************************
// no interceptor for [ST]
// **************************************************************************
// no interceptor for [int]
// **************************************************************************
// no interceptor for [double]
// **************************************************************************
// no interceptor for [bool]
// **************************************************************************
// no interceptor for [String?]
// **************************************************************************
// no interceptor for [void]
// **************************************************************************
// interceptor for [generics_module.SimpleGeneric<generics_module.Param>]
//parametrized type
class $generics_module_SimpleGeneric_generics_module_Param_
    extends generics_module.SimpleGeneric<generics_module.Param>
    implements Pluggable {
  $generics_module_SimpleGeneric_generics_module_Param_() {}
  T plugin<T>() {
    throw new Exception('no plugin for this type');
  }
}

// **************************************************************************
// no interceptor for [A]
// **************************************************************************
// no interceptor for [B]
// **************************************************************************
// no interceptor for [generics_module.ComplexGeneric<generics_module.Param,A>]
// **************************************************************************
// interceptor for [generics_module.SimpleGeneric<Foo>]
//parametrized type
class $generics_module_SimpleGeneric_Foo_
    extends generics_module.SimpleGeneric<Foo> implements Pluggable {
  $generics_module_SimpleGeneric_Foo_() {}
  T plugin<T>() {
    throw new Exception('no plugin for this type');
  }
}

// **************************************************************************
// no interceptor for [generics_module.SimpleGeneric<T>]
// **************************************************************************
// no interceptor for [GenericRootClass<Foo>]
// **************************************************************************
// **************************************************************************
class $ObjectManager {
  $nested_module_CombinedFoo? _nested_module_CombinedFoo;
  $nested_module_CombinedFoo get nested_module_CombinedFoo {
    if (_nested_module_CombinedFoo == null) {
      _nested_module_CombinedFoo = new $nested_module_CombinedFoo();
    }
    return _nested_module_CombinedFoo as $nested_module_CombinedFoo;
  }

  $nested_module_Foo? _nested_module_Foo;
  $nested_module_Foo get nested_module_Foo {
    if (_nested_module_Foo == null) {
      _nested_module_Foo = new $nested_module_Foo();
    }
    return _nested_module_Foo as $nested_module_Foo;
  }

  $nested_module_FooChild? _nested_module_FooChild;
  $nested_module_FooChild get nested_module_FooChild {
    if (_nested_module_FooChild == null) {
      _nested_module_FooChild = new $nested_module_FooChild();
    }
    return _nested_module_FooChild as $nested_module_FooChild;
  }

  $foo2_module_Foo? _foo2_module_Foo;
  $foo2_module_Foo get foo2_module_Foo {
    if (_foo2_module_Foo == null) {
      _foo2_module_Foo = new $foo2_module_Foo();
    }
    return _foo2_module_Foo as $foo2_module_Foo;
  }

  $bar_module_Bar? _bar_module_Bar;
  $bar_module_Bar get bar_module_Bar {
    if (_bar_module_Bar == null) {
      _bar_module_Bar = new $bar_module_Bar();
    }
    return _bar_module_Bar as $bar_module_Bar;
  }

  $bar_module_BarChild? _bar_module_BarChild;
  $bar_module_BarChild get bar_module_BarChild {
    if (_bar_module_BarChild == null) {
      _bar_module_BarChild = new $bar_module_BarChild();
    }
    return _bar_module_BarChild as $bar_module_BarChild;
  }

  $generics_module_Param? _generics_module_Param;
  $generics_module_Param get generics_module_Param {
    if (_generics_module_Param == null) {
      _generics_module_Param = new $generics_module_Param();
    }
    return _generics_module_Param as $generics_module_Param;
  }

  $generics_module_SimpleSpecific? _generics_module_SimpleSpecific;
  $generics_module_SimpleSpecific get generics_module_SimpleSpecific {
    if (_generics_module_SimpleSpecific == null) {
      _generics_module_SimpleSpecific = new $generics_module_SimpleSpecific();
    }
    return _generics_module_SimpleSpecific as $generics_module_SimpleSpecific;
  }

  $generics_module_SimpleGeneric_generics_module_Param_?
      _generics_module_SimpleGeneric_generics_module_Param_;
  $generics_module_SimpleGeneric_generics_module_Param_
      get generics_module_SimpleGeneric_generics_module_Param_ {
    if (_generics_module_SimpleGeneric_generics_module_Param_ == null) {
      _generics_module_SimpleGeneric_generics_module_Param_ =
          new $generics_module_SimpleGeneric_generics_module_Param_();
    }
    return _generics_module_SimpleGeneric_generics_module_Param_
        as $generics_module_SimpleGeneric_generics_module_Param_;
  }

  $generics_module_SimpleGeneric_Foo_? _generics_module_SimpleGeneric_Foo_;
  $generics_module_SimpleGeneric_Foo_ get generics_module_SimpleGeneric_Foo_ {
    if (_generics_module_SimpleGeneric_Foo_ == null) {
      _generics_module_SimpleGeneric_Foo_ =
          new $generics_module_SimpleGeneric_Foo_();
    }
    return _generics_module_SimpleGeneric_Foo_
        as $generics_module_SimpleGeneric_Foo_;
  }
}

$ObjectManager $om = new $ObjectManager();
//generated in 5ms
